### ISSUE TITLE
Retest Teamisland -> crash of program

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#334] opened 2015-12-23 21:59 UTC
Hi Guys!
I finally had time to retest the latest version. I started a new game with the version20151217. It seems it is a very good “test” map. 

Downloadlink:
https://www.sendspace.com/filegroup/sbYQPsR2dyMLZZYkIvSMmZoPKC%2BVBSIt

Crash 1: The whole program crashes. Can be reproduced with savegame: TotalCrash.sav
Crash2: Just wait till in the 2nd ship arrives and the program crashes. (Can be solved, by attacking the harbor before the ship arrives ;-) )

![crash after 2nd ship arrives](https://cloud.githubusercontent.com/assets/14259828/11985759/dc6bd8fc-a9a6-11e5-86c0-e2dc67af1969.PNG)

Crash3: Unfortunately that one is quite difficult to reproduce. I attached it, cause there was another report regarding this boarder issue.  It happened after I conquered one of the buildings. But I could not reproduce. 

![crash after atacks](https://cloud.githubusercontent.com/assets/14259828/11985829/93fd5090-a9a7-11e5-9415-2bb73ce78506.PNG)

Regards
David

**Comment by Heimbrent** [comment] 2015-12-23 22:25
Its a shame thats its not possible to play settlers 2 rttr, my game crashes after 1-10 minutes as I posted, with the nightly and I cant even open the game with the stable..
My christmas wish is to be able to play settlers, hope someone can fix this. (y)

**Comment by stefson** [comment] 2015-12-23 22:50
I'm willing to test, but cannot right now because of #332 , sry :)

**Comment by Heimbrent** [comment] 2015-12-23 23:14
:(

**Comment by stefson** [comment] 2015-12-23 23:18
The guys which are taking care of the programming will most likely need at least some debug output. For the linux version, you have to add a -gdb switch so to speak at the end of the commandline. Try to find out how this works on mac & post your logs here. Eventually use bpaste.net or something similar for the log itself.

**Comment by BlOedsin** [comment] 2015-12-23 23:29
Hi!

To avoid confusion. I am using PC (Windows 7), and retestet basically a former reported problem in sea maps. (See #313). I don’t think that my thread has anything todo with the problems of Heimbrent on Mac. I can start the game, and was playing for about 2h, till I had the first crash. I am using a couple of add-ons and I am playing a sea map, where I am aware, that instability might occur.  
@Heimbrent:
Please do not mix threads, as that might create confusion, and make it more difficult to fix the root course.

**Comment by Heimbrent** [comment] 2015-12-23 23:36
Im sorry, I will delete my comments above :+1: 
Thanks for letting me know.

**Comment by Flamefire** [comment] 2015-12-24 00:35
I'm also testing with this map. Showed a lot of issues before. I'll look into those issues...

**Comment by BlOedsin** [comment] 2015-12-24 16:33
The total crash happened to me, while I was playing for a while, out of “nothing”. I started the game with version 20151217 (normally updated via rttr.bat). I managed with the attack to get around the ship crash and continued playing. Unfortunately the last autosave before the crash was the one I uploaded to you (So very close to the actual crash). 

@replay files: I uploaded you the two replay files, which should be the one from the time of the crash. If I load them I only see a black landscape. Is it possible, as I am not the first player that it tries to record for the computer player? Can I change in a review file the player I want to see? 

@2nd ship crash: With the latest version it is a bit more “random” with me, when it exactly crashes. I attached you the Crash4.sav in case you want to investigate.
I think it is most of the time related, that when I connect a military building or build something on the island in the north, that this creates the crash (So I assume, when some goods need to be transported to the north; But as I said a bit random not all the time…) . But as I started the game with version 20151217 I am not sure how valid my tests are (Now I use version 20151223).
As you said you are anyway testing with that map as well, I think I will stop my tests for now, as it is probably faster for you if you first check the problems you find in your tests. If you want, send me a message, when you think the version is stable enough that I start again some “End-usertests”.

Downloadlink: https://www.sendspace.com/filegroup/VVT2EyVyBeT2m7598BMWbUio9Toifw7i

**Comment by BlOedsin** [comment] 2015-12-24 17:50
I think at least one crash I could reproduce (crash5).
As soon as my solder wins that fight and enters the building the program crashes. 
(Continued from above savegame on version 20151224)

![crash5](https://cloud.githubusercontent.com/assets/14259828/11996930/7244e1a6-aa4d-11e5-8e61-0c365413eb46.PNG)

Downloadlink: https://www.sendspace.com/file/64h6sc

**Comment by stefson** [comment] 2015-12-24 18:18
that one is reproduceable, see linked output from gdb. 

https://bpaste.net/show/f70223c0b435

**Comment by Flamefire** [comment] 2015-12-25 15:34
Feel free to test with latest version. I had 2 games with 6 ki without a crash so I need save games and more importantly replays of bugs. I'll look in into the crashes here tomorrow in the evening after I fixed the stuck soldier ;)

**Comment by Flamefire** [comment] 2015-12-27 13:24
@BlOedsin : For the replay and black screen, there is an open issue #324 You can press 'd' to toggle FoW or a number for switching to that player.

**Comment by Flamefire** [comment] 2015-12-27 14:15
It seems that the savegame is corrupted. The crash is unavoidable with that savegame so an earlier bug lead to that problem. 20151217 contained some bugs that were fixed now.

So I'll close this bug for now. Feel free to start new test games with the latest version. I keep on testing but also continue on other issues, so testers are really needed :+1:

**Closed by Flamefire** 2015-12-27 14:15 UTC

**Comment by Flamefire** [comment] 2015-12-27 16:09
For testing please use the latest version f7c2b2fe. This one should work now.

The black screen during replay is also fixed
