### ISSUE TITLE
Lobby chat notification color

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#585] opened 2016-08-23 16:38 UTC
When hosting a server there is the lobby chat and the game chat.
When you get a message, the buttons are blinking - sadly they use the wrong texture, currently IO id 8 is used but should be IO id 3.

Just have a look at the "Lobby Chat" button and "Return"

![lobbychat](https://cloud.githubusercontent.com/assets/1276342/17900764/bcf41c94-6960-11e6-8a1f-dd3abcdb444f.png)

**Comment by Flamefire** [comment] 2016-08-26 21:12
This was on purpose so the indicator is different than a button

**Comment by Spikeone** [comment] 2016-08-26 22:20
I understand that but the texture is just... there is a reason why it's never used - aybe use texture 6 instead, so it doesn't has the negative red color but looks highlighting?

**Comment by Flamefire** [comment] 2016-08-27 08:30
Why? I don't see a problem with that texture. I like it as a notification because it IS NOT used anywhere. So even if it was not flashing it would stand out as intended.

**Comment by Spikeone** [comment] 2016-08-27 09:59
Yes it is not used anywhere else but it is a texture that does not fit into the current design where we only use 0/1 2/3 and 6/7 for any button, Also texture changes (eg. for hoovering) always use the same type (eg 0/1/2/3/6/7; 4/5; 8/9; 10/11; 12/13/15; 14; 16; 17)
I don't see a reason either to change that for this one and only button as it doesn't look good - it's not that special.

**Comment by Flamefire** [comment] 2016-08-27 10:49
So your argument is basically: We did not use it in the past, let's not use it in the future?
We have a whole new case here: A flashing button. This is different than hover/press/whatever we used before, so IMO that IS a use for a new texture that is similar but different from the others because it means something new.
And "it doesn't look good"? I can hardly tell the difference to the other buttons if there wasn't another one close...

Hm, maybe anyone else with an opinion as a tie breaker?

**Comment by Spikeone** [comment] 2016-08-27 12:23
At first sight - yes thats what I'm saying.

But it's not about the texture itself, it's about the function of texture changes. The texture is the same but with other colors - this button changes color and texture which is just not like all other buttons - it's about keeping a design s2 and rttr has everywhere, not about blocking something new (the flashing button is something "new" as well) but texture + color changes is something new that doesn't fit into the current overall design.

But you are right, thats just an opinion as well (but also this fact hit me the first time I saw this flashing) - so yep, maybe anybody else maybe has an opinion or even a good reason why we should keep or change it :) 

PS: The feature itself is great!

**Comment by Flamefire** [comment] 2017-07-06 03:40
Could you make a mockup (paint...) of a texture you'd like and post the IDs to be used?
Only thing from me: It has to be different than the ones used before as it should show "notification available" not "I'm a button/tab" so it can't be the same as the "Return" button

**Comment by Spikeone** [comment] 2017-07-06 04:42
But in fact - it is a button. As for the same logic that button shouldn't use the normal button texture without notofication either?
But I'd agree, that using the "red" texture implies something bad. Maybe we should just hightlight the button instead? Well, when I'm home I'm going to test some of those ideas I got.

**Comment by Flamefire** [comment] 2017-07-06 05:07
We need different textures for different button states. We have "regular button", "dangerous button" and hovered and pushed versions of that. Now we need "highlighted button". That's what I mean. 
Actually it should be applicable to the "dangerous" one to but I don't know an easy way to make that.

**Comment by Spikeone** [comment] 2017-07-07 04:48
Checked it, there is no "better" texture. I was thinking about adding either a "unread messages" number for each "chat" (just a number field on the left and right) or maybe the dove as "message" indicator.

Or maybe just switch the texts color from gold to red to gold to red etc?

**Comment by Spikeone** [comment] 2017-07-08 16:23
![blinkblink](https://user-images.githubusercontent.com/1276342/27987226-807d6a86-640a-11e7-9950-00a1f60430a7.gif)

**Comment by Flamefire** [comment] 2017-07-09 01:20
It would be great if we had something more general. Because what we would need would be 2 types of buttons: normal and "dangerous" and for each type we need the different states: normal, hovered, pressed/activated, disabled and highlighted.
Adding an icon looks quite good, but is hard to make that general. Even worse: We don't know how long the text will be in all languages. So it could be over the button text, hence I'd like another color/texture better.

**Comment by Spikeone** [comment] 2017-07-09 09:12
Do we really translate "Lobby Chat"? I mean, thats a normally used term so I see no reason to translate that in general.

In most games, when a button "should be pressed" it just changes its state from hovered -> normal -> hovered without regarding if the control is hovered or not.
I can't remember a game which actually uses 3 colors (not regarding "grey" disabled).

Some more approaches:
Red text
![rt](https://user-images.githubusercontent.com/1276342/27992553-686a819e-6497-11e7-8cde-cc7f578e2d9a.gif)

Hover color
![hb](https://user-images.githubusercontent.com/1276342/27992556-712fd3a6-6497-11e7-8ba7-1a318c361818.gif)

Red text hover color
![hbrt](https://user-images.githubusercontent.com/1276342/27992558-77a9a7de-6497-11e7-86e3-69e0bf59c6d4.gif)

I really like the hover version. It feels like a normal dialogue in any program.

**Comment by Flamefire** [comment] 2017-07-09 10:59
I agree. The hover version is great

**Closed** 2017-07-21 11:38 UTC
Labels: enhancement
