### ISSUE TITLE
Mouse is not useable in full screen mode

### ISSUE THREAD

**Issue by Th0m45G** [Return-To-The-Roots/s25client#806] opened 2018-01-26 22:16 UTC
I played full screen 1920x1080 for some days. Today i started RTTR and the mouse cursor is jumping over the screen when i move it. In windowed mode it works fine, but full screen it doesn't.. :(

**Comment by Flamefire** [comment] 2018-01-27 15:43
Confirmed. But I don't know what causes this. Could not find any obvious bug in our code... I'll keep looking. Try a maximized window in the meantime

**Comment by Th0m45G** [comment] 2018-01-27 17:33
The stable version works. The latest nightly shows this error, so it must be one of the latest changes?

**Comment by Flamefire** [comment] 2018-01-27 20:10
It also happens in the main menu when slightly moving the mouse but occurs completely randomly. I could not find something that triggers it reliably. Tested with SDL.
Also tried to debug with log entries and could not reproduce it then. Might just have been bad luck though. Will check further

**Comment by Flamefire** [comment] 2018-01-30 17:13
I found the issue: A change in Windows is causing the bug. It doesn't seem to be well known but I found 1 other reported location: https://github.com/joncampbell123/dosbox-x/issues/331#issuecomment-351940759
This is probably due to SDL2 not triggering this issue.

In short: A timing issue in the mouse position handling in fullscreen mode leads to duplicated move events. So the actual (valid) event is duplicated many times (amount is random) which cause e.g. a 1px movement to be a 200 x 1px = 200px jump.

I see how we can mitigate this or if we have to patch SDL itself.

**Comment by Flamefire** [comment] 2018-01-30 20:28
Fixed with 7ba2df703683cd48de98a6128ecfe5e1ad4eac80

**Closed by Flamefire** 2018-01-30 20:28 UTC
Labels: bug

**Comment by Dpunkt** [comment] 2018-02-03 11:32
I don't think this issue is fixed completly. My Mouse Cursor does now move kind of sticky/slow/delayed.
SDL with disabled "Smart Cursor" worked.
Using WinAPI with "Smart Cursor" enabled worked.

I used nightly 20180130 7ba2df7  .

**Comment by Flamefire** [comment] 2018-02-03 11:55
I've noticed that WinAPI in full screen makes the cursor slow (windows issue) but not SDL. We query the cursor with 60FPS so in SDL  should not be such a problem.

SDL with disabled smart cursor did not jump for you? For me the issue was that the cursor jumped even in the main menu when just moving the mouse. So that was unrelated to smart cursor (which only moves the cursor when a dialog is opened)

Are you using windows 10 with all updates?

**Comment by Dpunkt** [comment] 2018-02-03 12:11
I use Windows 7.
Slow is not the right word, greasy would be more accurate. I do not see any Jumps, but the Cursor continues moving....

Tested on 2 Devices. Window Mode works fine, Fullscreen not.

Disabeling "Smart Cursor" reduces the greasyness in Fullscreen, but is more greasy in windowed then "Smart Cursor" Enabled.

**Comment by Dpunkt** [comment] 2018-02-03 12:12
I did not use the older nightly, so i did not see any jumps
