### ISSUE TITLE
Fix Russian language 

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#394] opened 2016-02-19 12:52 UTC
Currently there is a language file but the glyphs seem to be missing so no text is displayed

**Comment by Flow86** [comment] 2016-02-19 14:28
I think there is another issue about this.

To fix it, we have to add the correct russian/kyrilic letters into the file

OUTLINE_FONTS.LST

(in there are those 3 fonts used by the game)

I really don't know anymore if the fonts are already changed to utf-8 or not, if not, we have to do so, so we can have "all" letters in the fonts.

**Comment by Flow86** [comment] 2016-02-19 14:29
duplicate of #79

**Closed by Flow86** 2016-02-19 14:29 UTC
Labels: bug
