### ISSUE TITLE
Crash on sea map

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#355] opened 2016-01-10 11:45 UTC
A crash on a sea map. I do not see a direct reason, but as some ship returned after an attack, maybe there are some problems related to it?!?
Replay and savegame attached:

https://www.sendspace.com/filegroup/N9W%2BBPkKr7vyDS%2B4ZGTKlQ

**Comment by Flamefire** [comment] 2016-01-14 18:59
I was not able to reproduce this. Can you check if you can? Basically: Load the replay with the version you created it, jump to the end and press "p" to continue. If it instantly crashes, you could reproduce it.
If it crashes, check with the latest version if it still happens. Did not for me...

**Comment by BlOedsin** [comment] 2016-01-15 10:58
I could not reproduce it in the replay as well! 
Only if I load the savegame at GF 236499 it crashes.
I update to the latest version, loaded the savegame and the crash happened again. And again not in the replay (If I press p to continue in the replay it is not crashing!)
I know it should be possible to reproduce in the replay, but in that case I can only reproduce in the savegame. My version with which I tested today was: 20160114
I also transmitted the crash report today 11:57 MEZ, but I assume that you can reproduce it as well with the savegame.

**Comment by Flamefire** [comment] 2016-01-15 13:32
I loaded your savegame and run it past 236499. I used following versions:
- 20160106 i386 and x64
- 20160114 i386 and x64

Which OS are you using?

I can currently not access the crash reports. @Flow86 Can you set up the password and maybe delete all current crash reports so we see only new ones?

**Comment by BlOedsin** [comment] 2016-01-15 13:43
Win 7; 64bit
RTTR - v20160114-fd8c654
Just let me know, if and how I can provide you a better error report so you can reproduce it.
Just that we talk about the same savegame: Path...010

**Comment by BlOedsin** [comment] 2016-01-15 13:46
A bit before, that harbour was destroyed. Thats why my theory was, that it is somehow related to that...
![crash pathingding2](https://cloud.githubusercontent.com/assets/14259828/12354498/b5dcd45a-bb96-11e5-8582-aa9d2b30b904.PNG)

**Comment by Flamefire** [comment] 2016-01-15 13:47
This is really strange. And that bug always happens at 236499?
I'm also on Win7, 64bit and yes I'm using Path...010.

Can you come to IRC to talk?

**Comment by Flow86** [comment] 2016-01-15 13:49
Stacktrace:

```
000: 0x000000000044e6aa
001: 0x00000000db3976cf
002: 0x00000000db477ce0
003: 0x0000000000000002
004: 0x00000000db4cac30
005: 0x000000000142d900
```
-----------------------
```
000: 0x000000000044e6aa
001: 0x00000000ec65834f
002: 0x00000000ec657c8b
003: 0x00000000778e5210
004: 0x000000000142cb40
005: 0x000000000044e6aa
006: 0x00000000ec65834f
007: 0x0000000000020500
008: 0x0000000000000300
009: 0x00000000001ffaf5
010: 0x000000000324aaa0
011: 0x0000000000000100
```

**Comment by Spikeone** [comment] 2016-01-15 13:52
Do you use auto save each 500GF? Those crashs at GFXXXX99 are often related to saving.

**Comment by Flamefire** [comment] 2016-01-15 13:56
@Flow86 How can I convert those stacktraces to function names in windows?
@Spikeone: Good idea. Will test this too

**Comment by BlOedsin** [comment] 2016-01-15 13:56
@Spikeone: thats it --> changed it to a higher value and it did not happen

**Comment by BlOedsin** [comment] 2016-01-15 13:57
I tried a manual save which was working --> will try now to wait till the next autosave

**Comment by BlOedsin** [comment] 2016-01-15 13:58
@IRC yes I can where exactly?

**Comment by Flamefire** [comment] 2016-01-15 14:01
Server: irc.freenode.net:6667
Channel: #siedler2.5

**Comment by Flamefire** [comment] 2016-01-15 14:06
Yep, autosave triggers the error. I will see if I can find why.

**Comment by Flamefire** [comment] 2016-01-15 14:47
Yep, autosave triggers the error. I will see if I can find why.
The bug cannot be reproduced with VS2012 and it can also not be reproduced with the i386 build of rttr but only with x86_64
@Flow86: Is it possible to get a debuggable version from the build server?

**Comment by Flow86** [comment] 2016-01-15 14:49
yes you can download the debug symbols

**Comment by Flamefire** [comment] 2016-01-16 13:08
I opened the exe that crashed before in gdb for windows. It did not crash. Running the exe directly crashes. How is this possible?

**Comment by Flamefire** [comment] 2016-01-16 20:14
Ok current status: The crash happens only with the x64 version on windows, not with the 32 bit version. Also building with VS in either mode and running this won't crash. Executing s25client from within gdb in windows does also not crash. Attaching gdb to a running version of the x64 build-server s25client does crash when trying to execute a NULL-ptr
Backtracing does not work, as it shows the stack as corrupted. A guess from the registers returns the SerializedGameData::PushObject function at line 298 which should push the "security code". Not sure if this is correct, but it is possible.  Another try with "backtrace full" got me the call `go->Serialize(*this);` while `sgd.PushObject(attacker, true);` in `nofAggressiveDefender` was executed.
I doubt however that this is a real problem with the data structures/ the game logic itself, as it does not explain, why this does not happen for VS x64 or all 32 bit builds.

**Comment by Flow86** [comment] 2016-01-17 09:39
sounds like you access a deleted or uninitialized object (which often works on 32bit and inside the debugger)

perhaps try to run with valgrind?

**Comment by Flamefire** [comment] 2016-01-17 10:13
Is suspect the same. Especially as its an attacker. However VS has also checks for accesses to deleted/uninitialized objects (it overwrites the memory on alloc/free) so I though it would already detect this...
There is no valgrind for windows and I destroyed my linux VM (valgrind is not running well in a VM though) so I can't test that right now

**Comment by Flamefire** [comment] 2016-01-19 22:55
Bug is found. The reason for this is that the system for the AggressiveDefender is completely broken. I assume, that void `nofAggressiveDefender::AttackerLost()`/`nofAttacker::AggressiveDefenderLost` should have been used to unlink an attacker from an AggressiveDefender and `nofAttacker::LetsFight` should have been used to link them. However this is not the case and `AttackerLost` is never called by anyone.
I failed to find, when this bug was introduced, as it seems to be before the beginning of the git history.

As far as I can see the only thing missing here is a member for the AggressiveDefender the attacker is hunted by and the corresponding link/unlink calls. The savegame cannot be rescued by this as it will be invalidated by that change and already contains the bug (attacker is walking home, still chased by the defender ^^). However this bug will then be completely avoided

**Comment by Spikeone** [comment] 2016-01-20 07:14
As far as I understand those solutions (it's quite early) none of them are correct.
5 soldiers attack, 5 soldiers try to defend (from different buildings).
Now those 5 soldiers have their chase target, if a target is killed and there is an other soldier in range (walking but not chased or already waiting in front of a building), the defender will attack that soldier, otherwise he will leave and go back home.
Same happens when "counter" attacking, when a soldier is close to an other hostile soldier and they are both not chasing they will fight. I also think a fighting soldier who kills his enemy can stop a chasing soldier.

But I'll try to test this as well (still have no idea how "serfs find home" works in s2)

**Comment by Flamefire** [comment] 2016-01-20 09:21
Ok, I try to explain the first solution: Lets call them attackers and defenders. Each of the defenders have an attacker, they are chasing (defender goes after attacker, not the other way round) each of the attackers can intercept a defender or vice versa (this happens when ANY attacker and defender are close enough and can fight on a close spot) The defender, that was actually chasing that soldier will see, that he is busy, and choose another soldier to chase. In the 5vs5 scenario there would be none (all soldiers have already a chasing defender) and he would go home. If the defender wins, he will chase after his original attacker or intercept another one if one is close.

Is this what you mean? Or should a defender just go to his attacker and attack him without any interception? If the defender walks straight to its target attacker, but any attacker can intercept a chasing defender, then the situation would be the same as above.   
If an attacker, who is chased, cannot intercept any soldier, this would be bad as he won't be able to fight and the chasing defender might need ages to arrive. This is why, I'd implement this as above: Go after a main attacker, but just participate in the big battle (with the slight preference to the main attacker, as he walks towards him, when in doubt) For your 5v5 this would mean, as soon as one of the attackers start fighting vs another soldier that is not the chasing defender, this defender would go home (target busy and no other unchased soldier available) I think this is ok, as the attacker might get killed or at least wounded.

Maybe we can also say, we don't go home, if the target attacker is fighting but is still far away (however normally this should not be the case, as aggressive defenders start from nearby buildings)

**Comment by jhkl** [comment] 2016-01-20 20:45
Yep, each defender should pursuit one attacker. When other enemies get into close range with a defender, they are also getting engaged. Once the hunted attacker is killed (or unavailable for fighting when being close), the defender returns home. While returning home the defender still engages enemies when getting close to them.

**Comment by Flamefire** [comment] 2016-01-20 21:26
Perfect. Thanks for the explanation. I implemented it like that now and added multiple assertions so this bug can never happen again or will at least be detected. Will fix this with a PR later

**Comment by Flamefire** [comment] 2016-01-20 23:29
PR opened. Note that the replay above can be used with the version from the PR if the version is adjusted. (in RTTR or the replay) as the savegame in the replay did not contain attackers. It doesn't even go async in a short test...

**Closed** 2016-01-24 12:01 UTC
Labels: crash, question
