### ISSUE TITLE
s25rttr binary crashes on arm 

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1141] opened 2019-11-25 17:38 UTC
this used to work a few days ago: 

```
Program received signal SIGTRAP, Trace/breakpoint trap.
0x76f1e6e0 in raise () from /lib/libpthread.so.0
(gdb) bt
#0  0x76f1e6e0 in raise () from /lib/libpthread.so.0
#1  0x004b3024 in Loader::GetArchive (this=<optimized out>, file=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/Loader.cpp:112
#2  Loader::GetArchive (this=<optimized out>, file=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/Loader.cpp:110
#3  0x004b7b78 in Loader::LoadFilesAtGame (this=0x717d6008, mapGfxPath=..., 
    isWinterGFX=<optimized out>, nations=...)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/common/include/helpers/MultiArray.h:73
#4  0x0058d7a8 in GameLoader::loadTextures (this=this@entry=0xeae84c)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/libs/common/include/s25util/SingletonImp.hpp:72
#5  0x004cee44 in dskGameLoader::Msg_Timer (this=0xeae7b8)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/desktops/dskGameLoader.cpp:108
#6  0x00603f80 in ctrlTimer::Msg_PaintBefore (this=0xe78288)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/controls/ctrlTimer.cpp:73
#7  0x005c8a5c in Window::Msg_PaintBefore (this=0xeae7b8)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/Window.cpp:493
--Type <RET> for more, q to quit, c to continue without paging--
#8  0x004c7aa0 in WindowManager::Draw (this=0x87eda0)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/WindowManager.cpp:68
#9  0x004abe44 in GameManager::Run (this=0x86b480)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/libs/common/include/s25util/SingletonImp.hpp:72
#10 0x00430a68 in (anonymous namespace)::RunProgram (options=...)
    at /usr/lib/gcc/armv7a-unknown-linux-gnueabihf/9.2.0/include/g++-v9/ext/new_allocator.h:89
#11 main (argc=<optimized out>, argv=<optimized out>)
    at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25client/s25client.cpp:440
(gdb) continue
Continuing.
Assertion failure in "GetArchive" at /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/s25main/Loader.cpp#112: helpers::contains(files_, file)

```

this might be related to the upgrade from gcc-8.3.0 to gcc-9.2.0, I'm going to roll back from an older backup and try again to verify. 

last working commit unknown at the moment, I'll edit this statement as soon as I know more.

**Comment by Flamefire** [comment] 2019-11-25 19:47
Duplicate of #1139

**Closed by Flamefire** 2019-11-25 19:47 UTC
