### ISSUE TITLE
Cannot load savegames

### ISSUE THREAD

**Issue by ubmarco** [Return-To-The-Roots/s25client#775] opened 2017-12-11 21:24 UTC
Hello,

I'm writing this issue after asking in the [forum](https://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1522).
I have a problem loading savegames in version `v20171203-16186a84c9e8a13a88c5ca9f36ed8f0ab3aca7de`.
When loading some (not all) single player savegames, I get an error saying `map transmission was corrupt`. When clicking on ok, I'm back in the single player menu. When ending the game I see this console log:
The console log:
```
Loading LST,BOB,IDX,BMP,TXT,GER,ENG,INI files from "/home/marco/.s25rttr/LSTS"
Loading "/home/marco/.s25rttr/LSTS/SOUND.LST": done in 0ms
finished in 1ms
Connection to 127.0.0.1:3.665
Successfully connected to localhost:3.665
server state changed to stop
client state changed to stop
Connection to 127.0.0.1:3.665
Successfully connected to localhost:3.665
FATAL ERROR: BZ2_bzBuffToBuffDecompress failed with code -8
server state changed to stop
client state changed to stop
Saeubere Texturespeicher: fertig (nach 1ms)
```

After restarting the game and loading above savegame again, I even get a reproducible runtime exception saying
```
Connection to 127.0.0.1:3.665
Successfully connected to localhost:3.665
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown error during reading /home/marco/.s25rttr/MAPS/ParadiseAuto-Save.sav
/opt/s25rttr/bin/../bin/rttr.sh: line 60:  5018 Aborted                 (core dumped) $cmd $DIR/../bin/s25client $*
An error occured: press enter to continue
```
This happens the next times as well. The first error `map transmission was corrupt` does not occur anymore.

I attached 4 zipped savegames. From these 4, only the manually saved file Paradise.sav can be loaded, the other 3 lead to above errors.

If you need more information, please come back to me.

[SAVE.zip](https://github.com/Return-To-The-Roots/s25client/files/1549418/SAVE.zip)

**Comment by ubmarco** [comment] 2017-12-12 19:38
I built s25client as you specified. I can run it through dbg but whenever I click on Singleplayer -> Load game the game fully freezes. I can't leave it and the mouse does not move anymore. No response to ESC or Ctrl-C. I opened another terminal using Ctrl-Alt-F1, started top and sent SIG15 (SIGTERM). The game does not react to the signal. When sending SIG9 (SIGKILL) the game ends and I'm back in gdb without useful information or stack trace.
I've seen in top that the games takes 100% of one core in 'freeze-state'.

I tried to rename the folder ~/.s25rttr to ~/.s25rttr_bak to check whether it helps if a new user configuration is used. When starting the debugger again, I get the problem from my other issue #777:
```
(ins)(gdb) run
Starting program: /home/marco/Downloads/s25client/build/bin/s25client 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Return To The Roots v20171212-16186a84c9e8a13a88c5ca9f36ed8f0ab3aca7de
Compiled with Gnu GCC C/C++ (6.3.0) for Linux 64 Bit

Starting in /home/marco/Downloads/s25client/build
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: File name too long: "/home/marco/Downloads/s25client/RTTR/languages/LC_CTYPE=en_US.UTF-8;LC_NUMERIC=de_DE.UTF-8;LC_TIME=de_DE.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=de_DE.UTF-8;LC_NAME=de_DE.UTF-8;LC_ADDRESS=de_DE.UTF-8;LC_TELEPHONE=de_DE.UTF-8;LC_MEASUREMENT=de_DE.UTF-8;LC_IDENTIFICATION=de_DE.UTF-8/LC_MESSAGES/rttr.mo"

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(ins)(gdb) 
```

But I'm on the machine which could - until now - start normally using the pre-compiled x64 binaries.
When running the pre-compiled installation, I receive the same 'locales' problem as state above too. When restoring the former ~/.s25rttr directory, the games starts normally.

Back to the self-compiled gdb instance, I tried to start a new game. That works. But when trying to save the game using the options menu the games freezes as above upon clicking the 'Save game!' button.
When using 'Resume last game' I come to the screen 'selection of maps' where the mouse pointer transforms into the moon, then the games freezes again and I have to kill it.

So, sorry, I can't deliver any stack trace right now. Any suggestions how to proceed from here? Did I miss something?

**Comment by ubmarco** [comment] 2017-12-12 19:51
fyi: I had to build libboost1.55-dev on my own as that package is not available for Xubuntu 17.04. I started the build using `BOOST_ROOT=/home/marco/Downloads/boost_1_55_0 ./cmake.sh --prefix=. -enable-debug`.

**Comment by Flamefire** [comment] 2017-12-12 20:36
The freeze on the load screen should be fixed by the recent commit. Noticed a problem with locales and sorting of that table leading to an infinite loop. It should be the same for "Save game".
Could you test that first and also the "resume last game"?

If that works please produce the stacktrace.

**Comment by ubmarco** [comment] 2017-12-12 21:35
Now I can go to the load and save screens, thanks. Saving games work. But when loading for example the save game 'starmie' or 'Starmie (auto save)', the game freezes instantly forever, the moony mouse freezes and I have to kill the game on another console. Interestingly, there is no CPU load in that moment. When loading the same map without gdb, I come back to the console with this again:
```
finished in 2ms
Searching for drivers in /home/marco/Downloads/s25client/build/lib/driver/video
Searching for drivers in /home/marco/Downloads/s25client/build/lib/driver/audio
Connection to 127.0.0.1:3.665
Successfully connected to localhost:3.665
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unknown error during reading /home/marco/.s25rttr/MAPS/starmie.sav
Aborted (core dumped)
```

**Comment by ubmarco** [comment] 2017-12-12 21:37
Resuming last game works as well, it loads the map that I just saved for testing purposes.

**Comment by Flamefire** [comment] 2017-12-12 22:32
A heisenbug, nice! I've got no idea where to look now. Are you able to trace this in gdb or at least add a bunch of printfs to the code to see where it hangs? I'd put a `std::cout << __FILE__ << "#" << __LINE__ << std::endl;` on pretty much every line of SavedFile.cpp and SaveGame.cpp to see where it hangs. At least on at the start AND end of function would help trace this down. As said: I can't reproduce this at all :(

**Comment by ubmarco** [comment] 2017-12-13 08:24
I'll try to investigate on my own. I know C well and C++ ok, so I think I can make my way through the code. May take some time, I'll come back to you.

**Comment by SettlerBerlin** [comment] 2017-12-13 16:54
Same Problem for MAC OS
FATAL ERROR: BZ2_bzBuffToBuffDecompress failed with code -8
This problem is now after automatic update s25client...
How can i start the game without automatic updates??

**Comment by Flamefire** [comment] 2017-12-13 17:27
The start script has a noupdate option. Just start it from command line.
I'll look into that later again...

**Comment by SettlerBerlin** [comment] 2017-12-13 19:17
Oh, i always start the game from the launchpad... The first start doesn't work, but the second.
Now i have a really new installation, copying the last release 16186a8 and my old windows installation is gone :( Starting from Launchpad is related with automatic loading but doesn't load saved game, same reason.
The saved game (2,7MB) is in Library path and some logs...fortunately

**Comment by ubmarco** [comment] 2017-12-13 19:54
How do I come back to the console after hitting a breakpoint to investigate? The game just freezes on a breakpoint and I have to kill it... seems there must be a solution to this. Which IDE do you use for debugging?

**Comment by ubmarco** [comment] 2017-12-13 20:07
Now I'm stuck in read_char.cpp in line 62, see screenshot.
![screenshot_2017-12-13_21-06-59](https://user-images.githubusercontent.com/839934/33960023-a5a3aefe-e049-11e7-9832-c1aa7b5b7229.png)

**Comment by Flamefire** [comment] 2017-12-13 20:13
Sorry I can't understand you. You may explain in German too if that's easier.

What do you mean by "first and second start"? What do you mean by "old windows installation"? I though you are on OSX? What exactly is gone? "Automatic loading" means "automatic updating"?

Background: When you connect, the server sends you map-meta-data (name, size). The client checks if it is already in `<cfgDir aka .s25rttr>/MAPS` (played maps folder) and if yes, send the checksum of to the server. If no or the checksum mismatches the server sends the map compressed with bz2. Once received it is uncompressed which seems to fail with '-8' which means 'output buffer to small'. This does not make sense, because that map was just compressed by the server and the size send to the client.

I think I may have found something. This might happen when saving a game, loading that, saving to the same name and trying to load that again. This shows a bug in the above algorithm. Will try a fix now

**Comment by ubmarco** [comment] 2017-12-13 20:23
@Flamefire you're talking to @SettlerBerlin, right? Can I do anything more for you?

**Comment by Flamefire** [comment] 2017-12-13 20:29
All good, found it. Thank you very much, your debugging helped: The file must be empty to show the error you posted. And yes, that is possible due to a bug. So all in all it was 2 bugs. Fixed with #779 (see there)

**Comment by ubmarco** [comment] 2017-12-13 20:55
Glad I could help. I tested your PR. The map now can get loaded. But when entering the game, I see all settlers moving for 1 second and then the game freezes. Other save games work normally. Is that related to these bugs or another problem?

**Comment by ubmarco** [comment] 2017-12-13 21:00
I checked all save games and this game freezing does only happen on the Paradise (auto save) game.

**Comment by SettlerBerlin** [comment] 2017-12-13 21:18
First / second start means starting the application in launchpad on mac os. First start terminal shows an error and second start "click on icon" starts application. Windows installation is my copy, the original files <the game> see youtube- rttr installation video (mac)

> I think I may have found something. This might happen when saving a game, loading that, saving to the same name and trying to load that again. This shows a bug in the above algorithm. Will try a fix now

This may be the problem...

**Closed** 2017-12-13 22:37 UTC

**Comment by Flamefire** [comment] 2017-12-14 09:40
@ubmarco all I can see is a couple of strong lags in both paradise saves a couple of seconds after loading. That might be the AI. But the game continues after the lags.
Does it completely stop for you? Is it always the same game frame?

**Comment by SettlerBerlin** [comment] 2017-12-14 19:36
ast login: Thu Dec 14 16:08:47 on console
server:~ user$ /tmp/rttr.command
-bash: /tmp/rttr.command: No such file or directory
server:~ user$

Thats the terminal output, second start "click on icon" starts new terminal and the game is loading without error. See here: [https://www.youtube.com/watch?v=GDOumWfYopU&list=PLB59CA3B7DBDABA68&index=2](url)

**Comment by SettlerBerlin** [comment] 2017-12-14 19:51
Thank you for bug fixing, my saved game works!!!!

**Comment by ubmarco** [comment] 2017-12-14 20:12
The game fully freezes only on one out of 5 save games. At the others I experience the same lags you mentioned just after showing the map. These lags go away after some seconds.
The save game that fully freezes is 'Paradise (auto save)'. It was saved at GF 300.000. In 3 attempts it froze at the same GF (300.012).

**Comment by SettlerBerlin** [comment] 2017-12-15 09:58
OHHH no!
Loading the latest update today and the saved game crashes after 1 or 2 seconds. Please insert an option to allow or disallow automatic loading updates from server during starting up the game!!
Terminal shows no error, but please return version from yesterday (14 hrs ago)

**Comment by Flamefire** [comment] 2017-12-15 12:00
As I said there already is such an option. Just start it from command line and pass 'noupdate'.
Which savegame crashes? Please attach it here

**Comment by SettlerBerlin** [comment] 2017-12-15 12:44
[Archipelag Sumary (Automatisches Speichern).sav.zip](https://github.com/Return-To-The-Roots/s25client/files/1562680/Archipelag.Sumary.Automatisches.Speichern.sav.zip)

**Comment by Flamefire** [comment] 2017-12-15 12:59
@SettlerBerlin Thanks. With that I can reproduce the bug. The error is in the savegame, although I don't know how it could happen. Was this game at any point saved with a much older version (older than a couple days)?

**Comment by Flamefire** [comment] 2017-12-16 00:20
Fixed :)

**Comment by ubmarco** [comment] 2017-12-19 07:41
fyi: My save game 'Paradise (auto save)' can be loaded now and does not freeze anymore. Thanks a lot for the time and efforts you invest to maintain such a great incarnation of the good old times.

**Comment by Flamefire** [comment] 2017-12-19 11:09
Great! I changed a lot of the server code, a change I wanted to do a long time ago. It makes the gaming smoother by reducing network lags and allows faster response times (command order to command execution, watch the flag or building placement!)
