### ISSUE TITLE
"B" causes crash without "Vertex Buffer Objects"

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#7] opened 2015-07-05 11:04 UTC
When you turn off "Vertex Buffer Objects" and then press "B" ingame (Which jumps to the last screen position) then your game crashs. When turning "Vertex Buffer Objects" on this doesn't happen.

**Comment by jhkl** [comment] 2015-07-27 11:53
Cannot confirm with x64 nightly build and x86 VS debug build.

Any other special conditions? (OS? Screen content? Resolution? ...)

**Comment by Spikeone** [comment] 2015-07-30 21:13
Depends on map, you should use an "old" map like Island of Hills, this map uses textures which aren't recognized by RttR so jumping to 0,0 crashes the game.

**Comment by MarcusSt** [comment] 2015-07-31 07:14
Duplicate of #37

**Closed by MarcusSt** 2015-07-31 07:14 UTC
Labels: bug, duplicate
