### ISSUE TITLE
rttr graphics/resolution problems on windows 10

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#235] opened 2015-08-21 11:07 UTC
rttr works fine on linux but on windows there're problems:

When I start it it's in 800x600 windowed winapi mode which is the only resolution working.

When I switch to 1366x768 resolution windowed I get this:
![winapi_windowed_1366x768](https://cloud.githubusercontent.com/assets/13797213/9406959/49b32cb6-4805-11e5-9bf9-e4aa9c5a31c6.png)

When switching to fullscreen I get this:
![winapi_fullscreen_1336x768](https://cloud.githubusercontent.com/assets/13797213/9406876/9a3946f8-4804-11e5-949d-1d6744162617.png)

When trying out sdl it works only windowed (fullscreen isn't saved until next start of rttr) and gives this:
![sdl_1366x768](https://cloud.githubusercontent.com/assets/13797213/9406892/bac08472-4804-11e5-9758-58f8bf8871b0.png)

I've an acer notebook with windows 10 x64. Integrated intel graphics and discrete nvidia 840m graphics card. I haven't had any similar issues with other games.

**Comment by Flow86** [comment] 2015-08-21 11:55
since I dont use windows 10 yet, I cant reproduce the problem here. 

Most of these problem occur if the installed graphics driver does not have a correct opengl support. Try to install the latest proprietary graphics driver package for your graphic card(s), perhaps the issue is resolved then.

whats your native display resolution?

**Comment by kyromaster** [comment] 2015-08-22 06:08
The native resolution is 1366x768.
The newest graphics drivers are installed and I didn't have the problems with any other games.
Fortunately it works on linux :)

**Comment by Flamefire** [comment] 2015-08-27 08:14
Would you happen to be able to help us with that? You'd need a Visual Studio version on your windows 10 PC and try to compile the program yourself. The instructions should be sufficient to do so, if anything is missing or you have problems tell us so we can extend the manual. After it compiled I'd like to go through some debugging with you (I don't have a Win 10 PC here so I can't test it myself but this should be fixed before release)

**Comment by kyromaster** [comment] 2015-08-27 09:13
Good idea, that's what I also wanted to propose ;)
I'll install the free VS2015 Community Edition and try to compile rttr.

**Comment by Flamefire** [comment] 2015-08-27 09:23
I'll be home in about 6.5-7.5 hours. Where are you from? Would you happen to be able to join IRC at that time? Just tell me your name or PM me in IRC then.

**Comment by kyromaster** [comment] 2015-08-27 10:20
I searched the site but I just can't find the instructions for compiling rttr. Where are they?
I just have one or two hours per day time at a computer, and no IRC client installed or ever used. But I can of course install it.

**Comment by Flamefire** [comment] 2015-08-27 10:56
Check the readme: https://github.com/Return-To-The-Roots/s25client (scroll down to "How to build")

IRC: You can use the web client at: http://siedler25.org/index.php?com=dynamic&mod=3

**Comment by kyromaster** [comment] 2015-08-30 16:01
Unfortunately the build didn't work. I chose the configuration "debug->x64" and got about 500 errors divided into:

Severity	Code	Description	Project	File	Line
Error	C1189	#error:  Macro definition of snprintf conflicts with Standard Library function declaration	s25util	C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h	1927

Severity	Code	Description	Project	File	Line
Error	C2220	warning treated as error - no 'object' file generated (compiling source file C:\Users\Michael\Desktop\s25client\src\CatapultStone.cpp)	s25client	C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h	1925

And then some linker errors which are IMHO caused by the above errors.

**Comment by Flamefire** [comment] 2015-08-30 16:18
Got to check those, but need VS2015 first. I think @Spikeone  compiled rttr with VS2015 successfully before?

**Comment by Spikeone** [comment] 2015-08-30 19:37
No, I didn't but I may use my VM to compile RttR then - On the other hand, got no graphics card then

**Comment by Flamefire** [comment] 2015-08-31 19:47
@kyromaster The latest version can be compiled with VS2015 now. You have to unpack the contrib archive again. Try again please.

**Comment by kyromaster** [comment] 2015-09-03 15:04
I finally managed to compile rttr in x86 mode :)
The executable is now in build/src/Debug, where do I have to copy the contents from s2?

**Comment by Flamefire** [comment] 2015-09-03 16:11
Into the build folder. Then you can simply run rttr (ALL_BUILD should be marked in bold)

**Comment by kyromaster** [comment] 2015-09-04 17:12
Finally it works. So now we can start debugging this.

**Comment by kyromaster** [comment] 2015-09-11 18:05
I found a fix :)
In the "compatibility" tab of s25client.exe, enable "disable scaling with high DPI" and everything works fine.

**Comment by Flow86** [comment] 2015-09-11 19:11
ah, okay we should perhaps add it in the application manifest, or using the winapi to disable that automatically

http://stackoverflow.com/questions/13858665/disable-dpi-awareness-for-wpf-application

**Comment by Flamefire** [comment] 2015-09-12 16:23
Can't this be solved "correctly" in the code? Otherwise I'd choose the manifest.

**Comment by Flow86** [comment] 2015-09-12 17:31
in the msdn article they say that the manifest is the prefered method

**Comment by Flamefire** [comment] 2015-12-31 00:16
@kyromaster Can you try again with new version and without the compatibility setting?

**Closed** 2015-12-31 00:15 UTC
Labels: bug

**Comment by kyromaster** [comment] 2015-12-31 06:21
Everything works fine now :)
Thanks for fixing this!

**Comment by Flamefire** [comment] 2015-12-31 12:39
You are welcome! Happy new year!
