### ISSUE TITLE
[Addon] Refund Resources

### ISSUE THREAD

**Issue by Vinkdicator** [Return-To-The-Roots/s25client#1149] opened 2019-12-31 02:27 UTC
Oftentimes I want to destroy my mines but wish that the food could be taken out of them first. I was thinking maybe an addon where the food (or water or iron etc) could be added to the refund portion when the building is destroyed could work.

**Comment by Spikeone** [comment] 2019-12-31 12:00
Well, that one is german as well (because they are quite old) but its a duplicate of #67

**Closed by Spikeone** 2019-12-31 12:00 UTC

**Comment by Flamefire** [comment] 2020-01-01 14:56
@Spikeone Maybe you could translate the old issues are copy request texts like this into the old issues when they appear?
