### ISSUE TITLE
Black screen after minimizing the game window

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#375] opened 2016-01-23 13:19 UTC
I assume it is a known bug, but as I did not find an issue for it, I decided creating one. 
If you minimize the game in window mode, and return to the game, you only have a black screen.

![1](https://cloud.githubusercontent.com/assets/14259828/12530324/33a6ca94-c1dc-11e5-85d5-d18eeb86e7ef.png)
![2](https://cloud.githubusercontent.com/assets/14259828/12530325/3558fcc2-c1dc-11e5-9a43-fce879963a8c.PNG)

**Comment by Flamefire** [comment] 2016-01-24 15:26
Can't reproduce this. Which version and OS are you using (32/64 bit?) and when do you minimize and you restore?

**Comment by BlOedsin** [comment] 2016-01-24 15:38
What do you mean with when? Do you mean in which screen? I start the game, went to options, minimized, and clicked on rrtr in the status bar again. The result is that black screen.
OS: Win 7; 64bit, 
Graphics: Intel HD Graphics 4000
Settings: See Screenshot

**Comment by Flamefire** [comment] 2016-01-24 16:43
Unfortunately I cannot reproduce it. Searching with google shows a few results about driver issues or SDL related incompatibilities. You can try the WinAPI driver and see if this helps.

**Comment by BlOedsin** [comment] 2016-01-30 12:18
If I change to WinAPI the behavior is much worse. You cannot nicely put it into a window and adjust the size… Neverthelesse, as soon as I minimize the window, it gets black, in the same way as with SDL.
PS: I updated the graphic drivers to the latest version, to ensure that is not an issue but still the same

**Comment by Flamefire** [comment] 2016-01-30 17:27
I fixed the resizing in WinAPI mode. I could however not reproduce the minimize bug. Can you test the latest version and if it happens again attach the generated log file please?

**Comment by BlOedsin** [comment] 2016-01-31 09:34
I just tried it with the latest version again, and figured out a strange thing. 
If I resize the window, it is NOT black anymore! So for me I have a workaround, but it is not really helping to solve the problem ;-)

**Comment by Flamefire** [comment] 2016-01-31 10:12
Can I get the log from the game after a black screen? I have an idea but need to be sure 
Cause the black screen and resize it again to make it show something again. Then send the log

**Comment by BlOedsin** [comment] 2016-01-31 10:54
Hi!
I did not see anything in the logfile. Cause the line:
`lade "./RTTR/MUSIC/.\RTTR\MUSIC\S2_Standard.pll"`
is the last one after starting.
When minimizing and resizing I did not find any log messages. 
Then I closed the program and got the last two messages. 

PS: timestamps before the log messages would be nice ;-)

```
Loading "C:/Users/[Benutzer]/Saved Games/Return To The Roots/CONFIG.INI": done in 0ms
searching for drivers in ./driver/video/*.dll
2 video drivers found!
searching for drivers in ./driver/audio/*.dll
1 audio drivers found!
Writing "C:/Users/[Benutzer]/Saved Games/Return To The Roots/CONFIG.INI": finished

Starte das Spiel
Loading "./GFX/PALETTE/PAL5.BBM": done in 1ms
Loading "./GFX/PALETTE/PAL6.BBM": done in 1ms
Loading "./GFX/PALETTE/PAL7.BBM": done in 1ms
Loading "./GFX/PALETTE/PALETTI0.BBM": done in 1ms
Loading "./GFX/PALETTE/PALETTI1.BBM": done in 0ms
Loading "./GFX/PALETTE/PALETTI8.BBM": done in 1ms
Loading "./RTTR/COLORS.ACT": done in 0ms
Loading "./RTTR/splash.bmp": done in 59ms
Loading "./DATA/RESOURCE.DAT": done in 102ms
Loading "./DATA/IO/IO.DAT": done in 30ms
Loading "./GFX/PICS/SETUP013.LBM": done in 10ms
Loading "./GFX/PICS/SETUP015.LBM": done in 10ms
Loading "./GFX/PICS/SETUP666.LBM": done in 11ms
Loading "./GFX/PICS/SETUP667.LBM": done in 11ms
Loading "./GFX/PICS/SETUP801.LBM": done in 12ms
Loading "./GFX/PICS/SETUP802.LBM": done in 12ms
Loading "./GFX/PICS/SETUP803.LBM": done in 12ms
Loading "./GFX/PICS/SETUP804.LBM": done in 13ms
Loading "./GFX/PICS/SETUP805.LBM": done in 12ms
Loading "./GFX/PICS/SETUP806.LBM": done in 11ms
Loading "./GFX/PICS/SETUP810.LBM": done in 12ms
Loading "./GFX/PICS/SETUP811.LBM": done in 11ms
Loading "./GFX/PICS/SETUP895.LBM": done in 10ms
Loading "./GFX/PICS/SETUP896.LBM": done in 11ms
Loading "./GFX/PICS/MISSION/AFRICA.LBM": done in 9ms
Loading "./GFX/PICS/MISSION/AUSTRA.LBM": done in 12ms
Loading "./GFX/PICS/MISSION/EUROPE.LBM": done in 12ms
Loading "./GFX/PICS/MISSION/GREEN.LBM": done in 12ms
Loading "./GFX/PICS/MISSION/JAPAN.LBM": done in 12ms
Loading "./GFX/PICS/MISSION/NAMERICA.LBM": done in 12ms
Loading "./GFX/PICS/MISSION/NASIA.LBM": done in 12ms
Loading "./GFX/PICS/MISSION/SAMERICA.LBM": done in 13ms
Loading "./GFX/PICS/MISSION/SASIA.LBM": done in 12ms
Loading ".\RTTR\MUSIC\SNG\SNG_0001.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0002.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0003.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0004.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0005.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0006.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0007.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0008.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0009.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0010.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0011.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0012.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0013.OGG": finished
Loading ".\RTTR\MUSIC\SNG\SNG_0014.OGG": finished
Loading LST,BOB,IDX,BMP,TXT,GER,ENG,INI files from "./RTTR/LSTS/"
Loading "./RTTR/LSTS/CLIENT.GER": done in 0ms
Loading directory ./RTTR/LSTS/CREDITS.LST
Loading "./RTTR/LSTS/CREDITS.LST/demophobie.bmp": done in 6ms
Loading "./RTTR/LSTS/CREDITS.LST/flosoft.bmp": done in 7ms
Loading "./RTTR/LSTS/CREDITS.LST/jh.bmp": done in 6ms
Loading "./RTTR/LSTS/CREDITS.LST/nastx.bmp": done in 8ms
Loading "./RTTR/LSTS/CREDITS.LST/oliverr.bmp": done in 6ms
Loading "./RTTR/LSTS/CREDITS.LST/spikeone.bmp": done in 6ms
Loading "./RTTR/LSTS/CREDITS.LST/z-stef.bmp": done in 6ms
Loading "./RTTR/LSTS/LANG.GER": done in 1ms
Loading "./RTTR/LSTS/OUTLINE_FONTS.LST": done in 25ms
Loading "./RTTR/LSTS/RTTR.LST": done in 0ms
Loading directory ./RTTR/LSTS/firework.LST
Loading "./RTTR/LSTS/firework.LST/1.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/2.player.bmp": done in 2ms
Loading "./RTTR/LSTS/firework.LST/3.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/4.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/5.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/6.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/7.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/8.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/9.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/10.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/11.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/12.player.bmp": done in 0ms
Loading "./RTTR/LSTS/firework.LST/13.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/14.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/15.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/16.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/17.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/18.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/19.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/20.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/21.player.bmp": done in 2ms
Loading "./RTTR/LSTS/firework.LST/22.player.bmp": done in 2ms
Loading "./RTTR/LSTS/firework.LST/23.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/24.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/25.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/26.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/27.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/28.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/29.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/30.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/31.player.bmp": done in 1ms
Loading "./RTTR/LSTS/firework.LST/32.player.bmp": done in 1ms
Loading directory ./RTTR/LSTS/io_new.LST
Loading "./RTTR/LSTS/io_new.LST/000.rle.nx10.ny10.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/001.rle.nx10.ny10.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/002.rle.nx12.ny12.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/003.rle.nx15.ny12.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/004.rle.nx14.ny13.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/005.rle.nx12.ny10.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/006.rle.nx37.ny49.bmp": done in 1ms
Loading "./RTTR/LSTS/io_new.LST/007.rle.nx17.ny23.bmp": done in 1ms
Loading "./RTTR/LSTS/io_new.LST/008.rle.nx7.ny12.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/009.rle.nx3.ny7.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/010.rle.nx11.ny11.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/011.rle.nx11.ny6.bmp": done in 0ms
Loading "./RTTR/LSTS/io_new.LST/012.rle.nx16.ny14.bmp": done in 1ms
Loading "./RTTR/LSTS/io_new.LST/013.rle.nx11.ny11.bmp": done in 1ms
Loading "./RTTR/LSTS/languages.ini": done in 0ms
Loading "./RTTR/LSTS/logo.bmp": done in 5ms
Loading "./RTTR/LSTS/menu.bmp": done in 247ms
finished in 966ms
Loading LST,BOB,IDX,BMP,TXT,GER,ENG,INI files from "C:/Users/[Benutzer]/Saved Games/Return To The Roots/LSTS/"
Loading "C:/Users/[Benutzer]/Saved Games/Return To The Roots/LSTS/SOUND.LST": done in 52ms
finished in 54ms
lade "./RTTR/MUSIC/.\RTTR\MUSIC\S2_Standard.pll"
Writing "C:/Users/[Benutzer]/Saved Games/Return To The Roots/CONFIG.INI": finished
Saeubere Texturespeicher: fertig (nach 1ms)

``

**Comment by Flamefire** [comment] 2016-01-31 14:11
The version with the fix was not yet out. Check the version from today once it is ready :)

**Comment by BlOedsin** [comment] 2016-02-07 10:07
If I minimize, there was no log.
After resizing, there was the following log, after which I had a normal screen again.

`Resized screen. Requested 951x878, got 951x878`

**Comment by Spikeone** [comment] 2016-04-30 22:16
Tested it on my machine, Win7 x64 - no problems (neither winapi nor sdl)

**Comment by Flamefire** [comment] 2016-04-30 22:20
This issue seems to occur only on certain drivers/hardware. There seems to be a missing resize event. Best would be to have someone with this issue to debug this (Visual Studio)

**Comment by BlOedsin** [comment] 2016-05-01 08:54
I can confirm, it still exists on my machine.

Debugging in visual studio is probably above my it skills. If you send me a DAU step by step instruction what to do, I am willing to try. I do have VS 2012 Express installed on my pc but my last c programming is more than 10 years ago, and c++ I never programmed….

**Comment by Spikeone** [comment] 2016-05-01 11:24
Is it a notebook or something like that? The window looks maximized but running a maximized window in 16:10 doesn't happen that often (I guess). (Graphics: Intel HD Graphics 4000 doesn't sound like a desktop pc)

Does this problem also appear if you select a lower resolution (e.g. 1440x900) and minimize/maximize the window?

**Comment by Flamefire** [comment] 2016-05-02 17:18
@BlOedsin Should be fixed now. Please test :)

**Comment by BlOedsin** [comment] 2016-05-03 19:03
I can confirm that I do not get any black screens anymore.

**Closed** 2016-05-03 19:15 UTC
