### ISSUE TITLE
Error initializing log: Could not open

### ISSUE THREAD

**Issue by FELiXik** [Return-To-The-Roots/s25client#761] opened 2017-11-18 19:15 UTC
Savegame version of currently installed version: 36
Savegame version of updated version: 36
You will be able to load your existing savegames.
Starting in C:\Settlers2gold
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not open C:\Users\Miroslav Slov├í─Źek\Saved Games\Return To The Roots\LOGS\/2017-11-18_20-06-30.log for writing

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by Shawn8901** [comment] 2017-11-18 19:24
Looks like this https://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1384&start=2 for me.

Root cause should be the special character in your username. 
The "bug" should be fixed in the current master branch, but there is no nightly build at the moment.

**Comment by FELiXik** [comment] 2017-11-18 19:28
ok, thank you for hint. I´ll try to create user without special chars and report result...

**Comment by FELiXik** [comment] 2017-11-18 23:51
yes, you were right

**Closed** 2017-11-19 11:35 UTC
