### ISSUE TITLE
Click registers before mouse move with a touchscreen

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#90] opened 2015-07-30 22:05 UTC
Playing v0.8 with a touchscreen is pretty tough because in the game (menus are working fine) the click is registered before the mouse is moved. All menus (including the ingame menu) are working fine.

Steps to reproduce:
 * Start the game
 * Click somewhere on the map via a touchscreen

What happens?
 * The click is registered and the popup opens (for the previous mouse location)
 * The mouse is moved to the new location

What should happen?
 * The mouse should move to the new location before registering the click (as it happens in the menu).

Marcus (marcus) wrote on 2012-12-06:	#1
What video driver are you using? In any case, try the other one.

Robert_Zenz (robert-zenz) wrote on 2012-12-08:	#2
lspci -v Edit (10.0 KiB, text/plain)
I fear I do not have the choice to use another display driver, as I'm sitting on an Intel-VGA-Controller and a touchscreen which registers as USB-Device (lspci -v and lsusb -v attached for the curios).

Robert_Zenz (robert-zenz) wrote on 2012-12-08:	#3
lsusb -v Edit (16.6 KiB, text/plain)

NastX (jtrampe) wrote on 2012-12-09: Re: [Bug 1085472] Re: Click registers before mouse move with a touchscreen	#4
No he didn't mean the hardware driver. He meant the ingame software driver.
Like in Windows you can choose SDL-OGL-Driver and WinAPI-OGL-Driver....

2012/12/8 Robert_Zenz <Robert.Zenz@gmx.at>:
[...]

Robert_Zenz (robert-zenz) wrote on 2012-12-09:	#5
Oh....I only have the option for SDL-OGL (as I'm on Linux)...I also tried with the Nightly 20121206 and there's the same.

NastX (jtrampe) wrote on 2012-12-09:	#6
Ok for Linux there are no other drivers.
There was once a GLWF-Driver but this has been discontinued i think.
So somebody should adress this!

https://bugs.launchpad.net/s25rttr/+bug/1085472

**Comment by Flamefire** [comment] 2016-01-21 23:24
Duplicate of #89

**Closed by Flamefire** 2016-01-21 23:24 UTC
