### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by Merri** [Return-To-The-Roots/s25client#152] opened 2015-08-04 00:20 UTC
Looking around it looks like there are no tests for anything. I find this a bit disturbing, because without tests it is hard to change any code as you can't be sure if things work correctly after a change or not. It is more like **assuming** what you understood of previous code was doing was somewhat correct and then change and hope you got both your change right as well as the workings of the original code.

Thus I suggest that for every changed function / method there should be a test written against it so that correctness of it is ensured. This will of course "waste" some time initially, but over time as test coverage improves it also becomes so much faster to develop as far less manual testing is required after changes. Also, this would really start hitting those bugs away!

I haven't written C++ in roughly 15 years so I don't know what tools are available for this. In case I do happen to get interested enough to begin refactoring it would greatly help if there were tests.

**Comment by Flamefire** [comment] 2015-08-04 06:57
Test for that code will be very hard to write. Dependencies all over the place...

**Comment by Merri** [comment] 2015-08-04 09:41
In that case wouldn't it help code quality quite a bit if new code would be written isolated enough that it would be easy to test, while providing a simple abstraction to old code so that a full rewrite isn't necessary?

**Comment by Flamefire** [comment] 2015-08-04 09:59
If you know how, certainly yes. But e.g. soldiers: An active soldier "consumes" a passive soldier, removing it from its building and possibly creating events... Nothing isolated by design.
Also how would you test the terrain renderer (or any window class rendering)?

**Comment by Merri** [comment] 2015-08-04 14:46
If nothing else, you can always test a single method: make sure it returns the expected results, check for edge cases and so on. End-to-end testing is a thing on itself, so what I suggest is to add the easiest level of testing and worry about more complex testing issues later. Keeping it simple is a good beginning.

Also, if a method does a whole lot of things and it makes testing hard because of that, it may be a badly written one.

**Comment by lweberk** [comment] 2015-08-04 15:04
Are there enough dev resources to cope with the additional workload (at least x2)?
Would reduction of complexity not already achieve a lot of that? Do we have a chicken or the egg kind of problem?

**Comment by Merri** [comment] 2015-08-04 15:42
Testing is always for the better. In short, time spent on writing tests is time saved from fixing bugs. So in a sense you don't need more devs to do that: just a different mindset on how you work with your code so that you can automatically ensure better quality. As end result you spend more time doing new features instead of spending time hunting and debugging for bugs, which I guess is where most of the dev time is spent on right now.

I'm certainly interested on helping out, but getting started is hard for many reasons; in my case, I need to learn C++, I need to learn the current codebase, I need to learn C++ conventions from other projects / read articles on that... the list goes on. I probably do some searching on testing C++ code to see if I can set up something simple.

**Comment by MarcusSt** [comment] 2015-08-04 18:50
@Flamefire is right. In RttR, a lot of code depends on a game world to be there. The game world is hard-linked to a viewer, which I unlinked a bit from view (OpenGL & rendering stuff) to implement observation windows. Then there are quite a lot of singletons that need to be there for many methods, leading to a giant chain of dependencies (see e.g. [GameManager::Run()](https://dl.dropboxusercontent.com/u/11244516/RTTR/GameManager%3A%3ARun%28%29.png)).

It would be great to sub-divide RttR into
* [Networking](https://dl.dropboxusercontent.com/u/11244516/RTTR/ServerClient.png) (different protocols; local, TCP, UDP, ..)
* GameCommand (Player -> Client -> Server -> Client -> Simulation)
* Simulation (gets GCs from server via Client)
  * SimulationEvent (simulation-internal event)
* World (read-only for everything but Simulation)
  * Building (just the logic)
  * Figure (just the logic)
  * WorldEvent (some event a client can receive)
* Gui
  * GuiBuilding (graphics only, may read Building)
  * GuiFigure (graphics only, may read Figure)
* Slave (connected to Simulation, gets events, can read world)
* Spectator (implements Slave, uses Gui)
* Dummy (implements Slave)
* Player (implements Slave, can also send commands)
  * Human (uses Gui)
  * Bot (some kind of AI)
     * Placeholder
     * AIJH
* Server
  * forwarding only, not connected to anything else
  * can be standalone
  * to prevent cheating, a Dummy can be attached to the server (LocalClient)
* Client
  * Connects to server
  * runs one simulation per client
  * forwards GCs
  * provides SlaveInterface (to access the world/simulation, get events)
  * provides ClientInterface (send commands directly to the server)

And so on..

**Comment by Merri** [comment] 2015-08-04 19:05
That separation seems pretty good!

The way I think things should progress towards a goal of tested code is to separate some small pieces of logic related to one particular thing, such as WorldEvent, take that logic, make it independent and refactor all usages to use it (even if it may be "dirty" in the legacy parts), write a test for it and keep going on until you have all of WorldEvent neatly separated and fully tested.

This is easier and more convenient to do than starting a major rewrite and then ultimately hitting a wall when attempting to merge branch with massive changes back into master, which may have had it's own share of incompatible changes. Small commits are win.

**Comment by lweberk** [comment] 2015-08-04 19:13
@Merri 
All very true in an ideal world of infinite resources. But it has 2 things that weight extremely heavy and make testing in strict static typed languages only viable in critical code (accounting core for instance). Those are:
* Cost; for each unit of code you have at least twice the testing overhead
* Test sclerosis; your code stops being able to move, which is specially nasty when you are refactoring sections of the codebase, which is something that is coming if not already happening.

**Comment by MarcusSt** [comment] 2015-08-04 19:14
I'd suggest doing that (if at all – we need more devs for that, as it is quite a lot of stuff to do) in a separate branch. Once again, the nightly seems pretty stable. It would really be great to have something like a "stable nightly" (last known stable nightly) tag or something. Maybe major/minor/stable nightly releases (x.y.z, where z is the "stable nightly version", 0 for real releases). That makes it possible to test new features on something that is known to be stable, so crashes/asyncs are most likly those of the new feature branch, and merge it only after ensuring stability (there needs to be some testing checklist, like test map + human AI + at least 1.000.000 GF without crash etc). This is what can be done before fully trying to implement "real" testing.

**Comment by Merri** [comment] 2015-08-04 19:37
I'll look into testing to see how hard it will be; ideally I'd like to get into master ASAP and simply keep pushing things into it often, because keeping a branch for a long time is nasty thing for productivity. But anyway, I'll study and try things over the couple of next days and see how plausible things are. I'll rather try and fail than fail before even trying.

**Comment by lweberk** [comment] 2015-08-04 19:44
@MarcusSt 
Brought that up in #145 , but got shot down pretty quickly.

**Comment by Flamefire** [comment] 2017-06-06 04:53
I close this as we now have tests. Would be great to have smaller modules, so I moved that into #638

**Closed by Flamefire** 2017-06-06 04:53 UTC
