### ISSUE TITLE
Interface disappears when resizing window on MacOS

### ISSUE THREAD

**Issue by BlueGone** [Return-To-The-Roots/s25client#1034] opened 2019-02-05 13:40 UTC
When resizing the window or switching between "fullscreen" and "windows" mode, the interface disappears, and only the shape of the UI is visible.
![Window post resize](https://i.postimg.cc/76YZShHX/Screenshot-2019-02-05-at-14-29-00.png "Screenshot :")
This issue seems really related to the issue #611.

MacOS 10.14.2
Nightly, up-to-date on master branch.
Built with Clang 5.0.2

**Comment by BlueGone** [comment] 2019-02-05 13:53
Precision: it seems to affect only ressources which were not loaded before the resizing. For exemple, if I start the game, then resize, the interface will appear blank, but the good texture will appear when hovering buttons. If I already hovered a button before resizing, the texture will not appear.

**Comment by Flamefire** [comment] 2019-02-05 14:01
The problem is presumptively that changing the video mode destroys the current OpenGL context leading to a loss of all textures. This explains the behavior in https://github.com/Return-To-The-Roots/s25client/issues/1034#issuecomment-460645034 as textures are never reloaded once they are loaded. The same happens on windows where a workaround is in place keeping the OpenGL context alive.

Can you try SDL2 as your video driver (rttr settings screen to switch)? I remember something that it should be fixed there.

**Comment by BlueGone** [comment] 2019-02-05 14:19
It gives different bugs.
If the settings are windows with SDL2, the window size doesn't match the content, which keep a constant resolution (800x600 i think). Black borders appear on the right and top of the content to fill the window.
If the settings are fullscreen with SDL2, the game crash on start with the following stacktrace :
```
RttR crashed. Backtrace:
0x10999b61b
0x10998ca23
0x7fff72dc8b3d
0x0
0x7fff7030686e
0x7fff71b0fb6e
0x7fff47d461f9
0x7fff47d45fc0
0x7fff46c2bb93
0x7fff46c2b3fd
0x7fff46c2b2d5
0x7fff44c4010e
0x7fff42ef1644
0x7fff42ef0102
0x7fff42eea165
0x109cb2521
0x7fff72bdded9
Connection to 5.9.167.129:4123
Successfully connected to debug.rttr.info:4123
```
and, eventually, never end without a manual SIGKILL (Ctrl-C, "Do you really want to terminate the program (y/n) :y" don't work).

**Comment by Flamefire** [comment] 2019-02-05 15:10
I can reproduce the black borders on linux but not the crash. Can you rebuild in Debug mode and attach gdb to get the crashing function?

**Comment by Flamefire** [comment] 2019-02-09 15:43
You can try the latest nightly with SDL2 which should work better.

**Comment by BlueGone** [comment] 2019-02-15 00:05
I'm sorry I've not answered earlier. The latest fixed the black border problem, but not the crash when fullscreen.
I solved my problem with codesigning gdb. But now the logs I got with gdb seems really useless: 
```
$ gdb Contents/MacOS/s25client
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from Contents/MacOS/s25client...done.
(gdb) run
Starting program: /Users/placaist/s25client/build/Contents/MacOS/s25client
[New Thread 0xd03 of process 82705]
[New Thread 0xe03 of process 82705]
[New Thread 0x1503 of process 82705]
During startup program terminated with signal ?, Unknown signal.
```

**Comment by Flamefire** [comment] 2019-02-15 08:20
Am I right that the crash happens when starting in full screen only? If so than https://github.com/Return-To-The-Roots/s25client/pull/1042/commits/37c1066438c6c7a56fdaedc22d00f3cea6154650 in PR #1042 will fix this. Use a window and maximize it till this is merged :)

**Comment by BlueGone** [comment] 2019-02-15 09:34
Yes, the crash happens when starting in fullscreen only. And yes, your PR fix it. Nice job, thanks.

**Closed** 2019-02-18 19:24 UTC
