### ISSUE TITLE
Create Game / Error windows can't be closed by right clicking

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#526] opened 2016-07-27 12:21 UTC
All windows can be closed by rightclicking into them, except the Error-window (for example if you hit resume last game without any savegame) and if you create a new multiplayer game the Create Game-window can't be closed by right clicking either.

**Comment by Flamefire** [comment] 2016-07-27 12:30
I'd leave this for error windows. They shut be more resistant to (accidental) closing. The other one should work though.

**Comment by Flow86** [comment] 2016-07-27 12:32
yep I agree to @Flamefire: Error windows cant be closed by right click, but all other should

**Comment by MarcusSt** [comment] 2016-07-27 16:01
It's not a bug, it's a feature!

**Closed** 2016-08-05 10:59 UTC
Labels: bug

**Comment by Spikeone** [comment] 2016-08-05 15:22
@Flamefire does the MessageBoxEx now also close if error is set to false?

**Comment by Flamefire** [comment] 2016-08-06 09:12
No, it does not. Message Boxes are considered important and cannot be closed by right-click
