### ISSUE TITLE
Game crashes when attempting to access lobby

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#683] opened 2017-08-26 19:22 UTC
When clicking _Loby_ button:

```
/Applications/s25client.app/Contents/MacOS/rttr.command: line 67:  4737 Abort trap: 6           ./bin/s25client
```
```
Process:               s25client [4982]
Path:                  /Applications/s25client.app/Contents/MacOS/./bin/s25client
Identifier:            s25client
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [4972]
Responsible:           s25client [4982]
User ID:               501

Date/Time:             2017-08-26 20:21:19.614 +0100
OS Version:            Mac OS X 10.12.6 (16G29)

Time Awake Since Boot: 35000 seconds
Time Since Wake:       720 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000103
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x103:
--> 
    __TEXT                 0000000100000000-00000001005cb000 [ 5932K] r-x/rwx SM=COW  /Applications/s25client.app/Contents/MacOS/bin/s25client

Application Specific Information:
abort() called
```

**Comment by Flamefire** [comment] 2017-08-27 18:13
I'm on it

**Comment by Spikeone** [comment] 2017-08-28 16:28
Also happens on win7 x64

**Comment by Spikeone** [comment] 2017-09-01 16:06
@Flamefire where is the nightly build including this fix? :(

**Comment by Flamefire** [comment] 2017-09-02 02:03
Seems to be a build server bug. Build succeeded but no update? @Flow86 Found a `ln: failed to create hard link` in the most recent (although failing) build
Have a look at #687 and merge that to trigger a rebuild (fixes the build failure too)

**Comment by Flow86** [comment] 2017-09-02 06:54
the `ln: failed to create hard link`  is not a problem (it retries with standard copy)

The problem is here:
```
[windows.i386] i686-pc-mingw32-gcc: /workdir/src/s25client/../win32/s25client.rc: No such file or directory
[windows.i386] i686-pc-mingw32-gcc: warning: '-x c' after last input file has no effect
[windows.i386] i686-pc-mingw32-gcc: no input files
[windows.i386] /usr/bin/i686-pc-mingw32-windres: preprocessing failed.
[windows.i386] make[6]: *** [src/s25client/s25client.res.o] Error 1
[windows.i386] make[5]: *** [src/s25client/CMakeFiles/s25client.dir/all] Error 2
```

thats why the builds fails

**Comment by Flamefire** [comment] 2017-09-02 06:56
Ok, but the build before succeeded but no new version was pushed. The rc bug is fixed in the PR mentioned just have to wait if it passes CI
Note: Website still says 0.8.1 as latest stable.

**Comment by Flamefire** [comment] 2017-09-02 08:45
Update is  out. Please test

**Comment by Spikeone** [comment] 2017-09-02 10:27
Crash is fixed, update is available but the register button is still missing - I'd still recommend to add one as it is a hint where to create an account.

If that button isn't added, at least the "continue" should be centered

**Comment by Flamefire** [comment] 2017-09-02 20:41
Sure you have the latest version? I readded the button and it is in the src. So it had to be there

**Comment by Spikeone** [comment] 2017-09-02 20:55
Homepage says:
Latest version: 
20170901 | 1297e19

Updater (rttr.bat) version:
20170901 | 2500eb0

So, I'm not sure :D

**Comment by Flamefire** [comment] 2017-09-02 21:41
Homepage is wrong. But bug found and fixed

**Closed by Flamefire** 2017-09-02 21:41 UTC
