### ISSUE TITLE
AI blocks gold in military buildings

### ISSUE THREAD

**Issue by DanielBryk** [Return-To-The-Roots/s25client#851] opened 2018-07-17 16:55 UTC
Hello! Lately I play a lot RttR and it annoys me that on large maps AI is not delivery gold to buildings (gold is blocked on military buildings) and RARELY there are more then 1 soldier in building... Any ideas how to make "gold" distribution, so I will not be forced to fight privates?

Cheers!

**Comment by Shawn8901** [comment] 2018-07-17 17:37
Short question, are you fighting against easy AI?
From my experience the AI handles gold very well. But the easy AI will skip gold calculation, because it should be easy ;-)

**Comment by DanielBryk** [comment] 2018-07-18 10:07
I tried Easy, medium and Hard AI - none of them are distributing gold to military buildings...

**Comment by Shawn8901** [comment] 2018-07-18 16:53
Can you please share your game settings? 
i have just checked it with the most recent build from rttr.info and on my default game settings with medium AI and for me it still works.

Maybe the issue is related to a game setting?

**Comment by DanielBryk** [comment] 2018-07-19 06:08
Actually, I didn't use any settings besides those default... I remeber that at first gameplays gold was distributed... but no longer is no matter what :/

**Comment by Shawn8901** [comment] 2018-07-19 08:56
Could you please attach a replay and/or the save game?

**Comment by Shawn8901** [comment] 2018-07-30 16:02
I am still requesting a save game of this

**Comment by Spikeone** [comment] 2018-11-09 12:34
Closing this as the report is incomplete and we can not test this issue.

**Closed by Spikeone** 2018-11-09 12:34 UTC
Labels: incomplete
