### ISSUE TITLE
Client terminates with std::out_of_range

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#347] opened 2016-01-02 22:29 UTC
After unpausing the client terminates with the following exception being thrown:

```
79630 = C0:21879 O:7;14130 I:65536:1915579
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
/home/moritz/s25rttr/bin/../bin/rttr.sh: line 60:  4312 Aborted                 (core dumped) $cmd $DIR/../bin/s25client $*
```

[2016-01-02_22-04-43.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/76412/2016-01-02_22-04-43.rpl.zip)

[2016-01-02_21-55-01.log.zip](https://github.com/Return-To-The-Roots/s25client/files/76413/2016-01-02_21-55-01.log.zip)

**Comment by Flamefire** [comment] 2016-01-03 14:17
The game went async and the async logging methods were faulty. This will be fixed in a few minutes.
Regarding the cause of the async: It seems like some invalid commands were sent. The new version will also help in finding how this could happen but I'll also test the multiplayer version and pause handling later

**Comment by mplatt** [comment] 2016-01-03 14:57
Interestingly enough this now seems to happen regularly when unpausing. Just had another occurence:

```
<SYSTEM> Game was paused.
<SYSTEM> The game was resumed.
7580 = C0:12726 O:7;8236 I:65536:76392
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
/home/moritz/s25rttr/bin/../bin/rttr.sh: line 60: 12181 Aborted                 (core dumped) $cmd $DIR/../bin/s25client $*
```

**Comment by mplatt** [comment] 2016-01-03 15:04
Or probably not related to pausing unpausing as this also happened mid game :smile: 

```
16910 = C30714:30714 O:19252;19251 I:245928:245927
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
/home/moritz/s25rttr/bin/../bin/rttr.sh: line 60: 12387 Aborted                 (core dumped) $cmd $DIR/../bin/s25client $*
```

**Comment by Flamefire** [comment] 2016-01-03 15:06
First async is related to pausing/unpausing. Fix is almost done. 3 minutes
The mid-game async is new. I'd need replays+savegames+logs, but wait for the update as it will create better logs/savegames

**Closed** 2016-01-03 15:12 UTC
Labels: bug, crash
