### ISSUE TITLE
Mapselection visible text bug

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#977] opened 2018-12-27 20:55 UTC
I've got a strange text bug everytime I list my "other" maps folder.

![image](https://user-images.githubusercontent.com/1276342/50494174-f4df8a80-0a21-11e9-8a3c-97c492c8baa0.png)

Here my other folder is (20mb): 
[OTHER.zip](https://github.com/Return-To-The-Roots/s25client/files/2713348/OTHER.zip)

**Comment by iceslab** [comment] 2019-09-11 19:51
It appears that's not a UI bug, but malformed author name in map itself.
![malformed_author](https://user-images.githubusercontent.com/10535944/64729761-bddcd680-d4d5-11e9-8550-209c0fa07ebd.png)

**Comment by Flamefire** [comment] 2019-09-29 11:38
Ok so the problem is a `\n` (newline) in a text coming from users. The (minor) problem: Parsing of newlines is a feature. We would need some infrastructure to explicitly disallow this or check for in things like the map name, author, ... This can be done on loading the map or just on some controls.
I guess for the list control used here we can do it on the control: On *NO* list control we want newlines in the rows.

Question: What to do with them? Print as `\n` literal or remove?

**Comment by Spikeone** [comment] 2019-09-29 12:20
In my opinion I'd simply (if thats simply) go for literal as for example if you have to authors who call themselves horst and ninja they might label the autor as horst\ninja - well thats not very probable but - well better see something than just removing it in my opinion.

**Comment by Flamefire** [comment] 2019-09-29 15:57
Kinda simple. I'll take a look at it once @Flow86 is back to merge PRs or allows to merge without his explicit review.

**Comment by Flamefire** [comment] 2019-11-09 17:19
I'm currently about to remove newline handling from the font rendering completely. We have ctrlMultiline and text splitting for creating multiple strings out of a string containing possible newlines.

The side effect is, that because `\n` does not exist as a glyph it will be rendered as `?` instead. I don't really want to implement replacement of such rare occurrences and rather use the "non-printable-character" replacement (in our case `?`) for that. As it is an error to include a newline in the map title I think this is appropriate.

What do you think?

**Comment by Spikeone** [comment] 2019-11-09 18:18
For me this sounds good enough. Althoug one could think about flipping it like ¿ just to make sure everybody sees this is an errorneous character and not a missplaced question mark.

**Comment by Flamefire** [comment] 2019-11-09 18:50
Yes. But maybe we use the proper one: https://www.fileformat.info/info/unicode/char/fffd/index.htm
Could you make them?

**Comment by Spikeone** [comment] 2019-11-10 09:41
Sadly there aren't much pixels yet any character is outlined in Settlers 2 which is why I kept it. Guess it suffices for it's use case.

![image](https://user-images.githubusercontent.com/1276342/68541957-73c58380-03a6-11ea-8c8e-18b1b0ea9326.png)

[U+fffd.zip](https://github.com/Return-To-The-Roots/s25client/files/3828284/U%2Bfffd.zip)

**Comment by Flamefire** [comment] 2019-11-10 11:55
The inside question mark should be transparent? I fear this might look bad on some backgrounds :/

But this is hard: There are only 4 colors available and black can't be used for it as it is removed for non-outline ones. Still keep them?

**Comment by Spikeone** [comment] 2019-11-10 13:37
Using maximum contrast (only light and dark blue):
![image](https://user-images.githubusercontent.com/1276342/68544831-679dee00-03c7-11ea-9d72-4f4a1da4978c.png)

Using an outline:
![image](https://user-images.githubusercontent.com/1276342/68544833-6f5d9280-03c7-11ea-8233-83f89e270a3f.png)

Using black instead of transparent:
![image](https://user-images.githubusercontent.com/1276342/68544840-784e6400-03c7-11ea-9e47-09dd9ecc2c6a.png)

One might increase the size by 1 pixel to have a border in the upper left - but I have no idea what happens if one glyph exceeds the common image size.

**Comment by Flamefire** [comment] 2019-11-10 13:51
The outline cannot be used, as everything but the player colors is removed for the no-outline variation. So IMO the max contrast is the best solution.   
As we do use almost always the outline version we could use the last one (black instead of transparent) which falls back to the transparent one for no-outline. Might look weird though, although it doesn't happen often (should at least)

> but I have no idea what happens if one glyph exceeds the common image size.

Technically we could freely exceed the width of the glyph. The height is assumed to be fixed. However if we want to support glyphs with bigger widths, some code change is necessary, although trivial.

**Comment by Spikeone** [comment] 2019-11-10 15:26
Personally I'd vote for going with either transparent or black question mark (so either my very first or very last version). 
As you also said, it shouldn't happen often so we should not put to much effort into this :)

**Comment by Flamefire** [comment] 2019-11-10 16:15
Ok, then black (which would be transparent for non-outline). Can you attach the glyphs?

**Comment by Spikeone** [comment] 2019-11-10 16:20
[U+fffd.zip](https://github.com/Return-To-The-Roots/s25client/files/3828684/U%2Bfffd.zip)

**Comment by Flamefire** [comment] 2019-11-10 17:52
Thanks. I packed that into the fonts LST and the size increased from 91kb to 469kb. Because the LST file stores 2 bytes of zeroes for each empty space we have 3*65k*2=390kb of zeroes in the file -.-

What about we simply ship the fonts as a folder? This makes updates easier as only a single file is added/changed/removed, not a binary blob. 
@Flow86

**Comment by Flamefire** [comment] 2019-11-13 17:48
The alternative would be to use a zip file. E.g. widelands is doing that: They have an abstraction where a zip file is handled like a folder. We have something similar with the `libsiedler2::Archive` (and probably need to handle the zip file at that level) But that requires adding another 1-2 dependencies: libzip and libminizip

Not sure...

**Comment by Flow86** [comment] 2019-11-13 20:24
> What about we simply ship the fonts as a folder? This makes updates easier as only a single file is added/changed/removed, not a binary blob.

we can do that too. but who cares if there are 400kb zeros in the file. I don't mind (bzip @ the updater neither)

> adding another 1-2 dependencies: libzip and libminizip

I don't like that, having another compression algorithm and external dependency.

**Comment by Flamefire** [comment] 2019-11-14 08:29
> but who cares if there are 400kb zeros in the file. 

True, but the git repo will care. Adding/changing a single glyph? Change of a 500kb binary file. A folder would solve that as the actual change is tracked 

> I don't like that, having another compression algorithm and external dependency.

External dependencies and C++, the never ending nightmare ;) BUT:
- Zip is not a compression algorithm, but a file format, it (may) use BZip2 (which is only a compression algorithm, it can't compress multiple files or even keep the filename)
- libz is probably installed already on all Unix-ish systems (and AFAIK part of MinGW base distribution)
- libz and libminizip-devel are available in most Unix-ish package repos
- Using zip instead of LST makes it much easier for users/modders as well as being smaller and can be read/written by all OSes "natively"
- libminizip is just one example. I found:
  - https://github.com/wdas/partio/blob/master/src/lib/io/ZIP.cpp IOStream based impl
  - https://bitbucket.org/wbenny/ziplib/src/master/Source/ZipLib/ C++11, stream based, but convoluted, not really trustworthy imo
  - https://github.com/ctabin/libzippp wrapper around libzip, which wraps zlib (why is ZIP so hard and names confusing?)
  - ...

Main point is usability. Currently it is pretty hard/cumbersome to change e.g. font glyphs as you have to use lstpacker to unpack and repack instead of simply zipping a folder with whatever tool you like. Not fully sure if it is worth the work though.

**Comment by Flow86** [comment] 2019-11-14 14:52
why not simply adding the single glyphs and use the directory (over)loading feature?

**Comment by Flamefire** [comment] 2019-11-14 16:13
Possible. But: Currently fonts are in `RTTR/LSTS` (which already is an override folder). Do you want to add an `RTTR/LSTS_Update` folder to contain updates to files in `RTTR/LSTS`? Or shall we evaluate using the original font lst and add our new glyphs to `RTTR/LSTS`?

**Comment by Flow86** [comment] 2019-11-14 16:19
we could extract the outline_fonts into RTTR/LSTS and only use the extracted version. Or - shouldn't it work having both in there? I don't remember how the override directories have to be named (i.e if they need the extension) otherwise it would not be a problem to have a outline_fonts.lst and additionals glyphs in there.

**Comment by Flamefire** [comment] 2019-11-14 20:53
> we could extract the outline_fonts into RTTR/LSTS and only use the extracted version

That's also what I proposed in https://github.com/Return-To-The-Roots/s25client/issues/977#issuecomment-552217379, would be easiest

> Or - shouldn't it work having both in there?

Might be better: Use LST for ASCII (dense, all existing) and folder for new ones?

> I don't remember how the override directories have to be named

Currently they have to be named exactly the same, hence they need to be in different folders. But I started with a different locator implementation a while ago: https://github.com/Flamefire/s25client/commit/8692cf29b75ea724046888ce9876acb5d4c1f0ad#diff-40433b2bd5f6123dd47eefd06432e821 We could choose to completely ignore the extension and simply say load a file with given stem (e.g. `tex5`). This would resolve to `[Tt][Ee][Xx]5.*` (pseudo) in any folder given earlier. Makes resolving slightly slower, but would work.

However for now I'd rather use an unpacked folder or a zip file. I fear an unpacked folder could kill the updater? It will pack and transfer every single glyph :/ Maybe just use the big LST now but decide and implement an alternative before changing it to keep the impact to the git repo minimal.

**Comment by Flow86** [comment] 2019-11-15 15:27
if the git repo is the "problem" - we still could add them to git lfs instead.

**Comment by Flamefire** [comment] 2019-11-15 15:49
True. Haven't though of that. So basically: All LST files should be put on git LFS.

I'm still in favor for having a usable, standard format that uses compression instead of the suboptimal S2 legacy stuff. But that can be discussed in a new issue.

**Closed** 2019-11-18 16:05 UTC
Labels: bug
