### ISSUE TITLE
Load-Screen flickering

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#532] opened 2016-07-29 12:11 UTC
Whenever I start a game, I get get a strange flickering when the loadingscreen picture contains black/dark colors. You can see the host menu in those areas flickering.
This bug already exists for very long.

See: https://www.youtube.com/watch?v=S7xx42q_GIQ

**Comment by MarcusSt** [comment] 2016-07-29 19:55
Seems to be fullscreen only here (see also #534).

**Comment by Spikeone** [comment] 2016-07-29 20:00
Tested it, for me it doesn't matter if windowed, fullscreen, vertexbuffer, optimizedtextures, winapi, sdl - this bug always appears

**Comment by Flamefire** [comment] 2017-11-04 13:49
Fixed with c8fccc7078d72e02daec960aa24be1c6667fd258

**Comment by Flamefire** [comment] 2017-12-06 21:49
Unfortunately this issue is not fixed yet. However I found the cause: We use index 254 for marking a transparent pixel in paletted images. This was wrong. You can see through the load screen because the pixels at these positions have index 254 in the file. This is different to loading e.g. rle images, where transparent pixels are explicitly marked.
Additionally the [LBM format](https://en.wikipedia.org/wiki/ILBM) has a field to define the index for transparent pixels and a flag to enable this at all. So our LBM (load screens) files should not be transparent at all according to the flag.
But again BB did not follow the format specifications. I checked the TEX<5-7>.LBM files where we do have transparency: The background of the edges and the ways. Here we have to use index 0(!) which is usually black. But in TEXTUR_3 it is not!
The transparency flag is always off, but the color index is set to 254. This is the background color which does not really matter to us. But interesting: in TEX7.LBM the color index is 0 and indeed the background color is (only in this image) black. It seems we should use that index **in addition** to the usual 0.

For the SETUPxxx.LBM this does not hold. In SETUP666.LBM we have only index 0 for black (in other palettes we do have another index that is black) and it is used. The transparency is off and the transparent color index is 255 which is (the only) white in the palette and that is also used. So here we should have no transparency.

My idea would be: Fix the code so transparency is 0. For the SETUP-images we draw them on a black background anyway. So that is no problem if black pixels are transparent.

**Comment by Flow86** [comment] 2017-12-07 11:26
No, I would not recommend to add 0 as a transparent pixel.

I dont think we check the transparency flag in lbms at all, so we should consider that (if its off, the transparency color should be mapped to 0)

**Comment by Flamefire** [comment] 2017-12-07 11:31
why not? Xaser in its editor used that and it seems that there is almost always a 2nd black value while there is no other 254 value.
I added a check for the transparency flag but it is always off even though it should be on in some. And even if it is off we have to set the transparency color to something or change the code to allow non-transparent images (unsupported ATM and requires major changes)

**Comment by Flow86** [comment] 2017-12-07 11:44
okay, then at least we have to document that properly inside the code

**Comment by Flamefire** [comment] 2017-12-07 12:00
I made some commits, most importantly: https://github.com/Return-To-The-Roots/libsiedler2/commit/1da612e190e4553c3af81212abec351b4166e6fd
And I also added a tool to convert the current (custom) LSTs like fonts.

**Closed** 2017-12-14 15:44 UTC
Labels: bug
