### ISSUE TITLE
Ki have problems with her Buildings 

### ISSUE THREAD

**Issue by Strawberry93** [Return-To-The-Roots/s25client#378] opened 2016-01-27 03:25 UTC
Ki Settings is hard to

![siedler bug 1](https://cloud.githubusercontent.com/assets/16910900/12602911/91195baa-c4ad-11e5-92ff-b55c0f9dc7f1.png)

**Comment by Flamefire** [comment] 2016-01-27 09:25
Thanks for reporting. The problem is known and fixed in 6d0059e8fd95fe34d05e38c13dbf2db712da7b34
Unfortunately we currently experience problems with the build server, so the new version is not yet there. Try an older version like 20160122 which does not have the bug yet, or wait for the new one once it is out (>=20160127)
If it happens again on the new version, please reopen

**Closed by Flamefire** 2016-01-27 09:25 UTC
