### ISSUE TITLE
Items are not being collected

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#349] opened 2016-01-03 16:23 UTC
In a past game, I was unable to move shields to a warehouse from the headquarters even though the warehouse had the *collect* flag set. Beer and shields were affected (see screenshot).

![screenshot from 2016-01-03 16 34 51](https://cloud.githubusercontent.com/assets/1663386/12079575/8b2d7400-b23e-11e5-80fa-2b880aa57184.png)

[warehouse_problem.sav.zip](https://github.com/Return-To-The-Roots/s25client/files/76653/warehouse_problem.sav.zip)

[2016-01-03_16-05-39.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/76655/2016-01-03_16-05-39.rpl.zip)

**Comment by Flamefire** [comment] 2016-01-03 16:28
Not completely sure, but doesn't "collect" mean, that the shields are stored in the wh instead of the HQ, but NOT that they will be moved without further reason? I think you would have needed to tick "send out" shields in the HQ for this to work

**Comment by mplatt** [comment] 2016-01-03 16:34
I always thought that the the collect feature was intended to collect wares from everywhere. If that wasn't the case, why would you need three modi (take out, stop storage, collect)? Then two would be enough, right?

**Comment by Flamefire** [comment] 2016-01-03 16:37
Well, obviously "take out" includes "stop". And "collect" includes "take" (no symbol). A wh with a "collect" will be considered over a "take" wh whenever possible. So in your case, if a shield is produced, it will always go to the wh, not the HQ. So it is similar to setting all others to "stop".
The difference: When a "collect" cannot be reached, a normal wh is taken. If you would have set all others to stop, then the ware would not go to any wh.

**Comment by mplatt** [comment] 2016-01-03 17:12
Not sure if I get 100% of what you're saying, sorry. But could you check the attached minimum example? The we have HQ (no flags set) and WH (collect flag set) and it works as I expect it. Note the saws being moved. No *send out* flag necessary in HQ.

[2016-01-03_18-05-07.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/76668/2016-01-03_18-05-07.rpl.zip)

**Comment by Flamefire** [comment] 2016-01-03 17:27
Ok will check that later

**Comment by Flamefire** [comment] 2016-01-03 18:58
Yep you are right. It should work like you described. Will check that.

**Comment by Flamefire** [comment] 2016-01-04 11:30
I tried the savegame. When I loaded it beer and shields were not marked as collect. Once I marked them, they got collected... Will check the replay though

**Comment by Flamefire** [comment] 2016-01-04 12:36
According to the replay you switched that setting on and of a few times (starting around GF 64500) resulting in a final "off" setting
In the replay I found it working and at least 1 shield IS transported (around 66k GF), so no, I can't see a bug here

**Comment by mplatt** [comment] 2016-01-04 12:39
Before that I had the setting on for a long time (30 mins +) with no
effect. Switching on and off was done to trigger one shield being moved.
This definitely did not work as intended.

**Comment by Flamefire** [comment] 2016-01-04 15:28
Can't see that in the replay... However if I jump to 64579 then shield collecting is enabled in the HQ not the wh. Can you find the position in the replay, where it is enabled but not working?

**Comment by Flamefire** [comment] 2016-01-04 19:09
Ok I think what happens is that the game shows you, that collecting is enabled, but it is not. So when you switched it off, it actually was on and working like it should. This can be caused by a dropped network packet e.g. while pausing the game. Did you pause the game before that bug occured?

Description and possible fix to prevent this from happening is in #350.

**Comment by mplatt** [comment] 2016-01-04 19:57
I assume your analysis is correct. For reference when I forward to GF 64942 *in the replay* the warehouse shows different flags then in the screenshot taken in game:

![screenshot from 2016-01-04 20 54 11](https://cloud.githubusercontent.com/assets/1663386/12098945/a24fe07c-b325-11e5-93ff-9bd0b39cd7dc.png)

And yes--this game might have had a pause and it certainly had a lot of connectivity issues.

**Comment by Flamefire** [comment] 2016-01-04 21:22
Alright. This was also the reason why I though I missed something because I could not get the image from your screenshot.

I made a commit so that GCs during pause are not dropped anymore. This should make this at least less likely. Tackling the root issue will be done in #350 

Thanks for helping :+1:

**Closed by Flamefire** 2016-01-04 21:22 UTC

**Comment by mplatt** [comment] 2016-01-31 20:27
This problem was still reproduceable today:

No flag in wh:
![screenshot from 2016-01-31 21 06 03](https://cloud.githubusercontent.com/assets/1663386/12704731/2ebae3b8-c861-11e5-870d-8c44374903e3.png)

Collect flag in wh:
![screenshot from 2016-01-31 20 38 21](https://cloud.githubusercontent.com/assets/1663386/12704734/4433a91e-c861-11e5-96a2-e854686f55a1.png)

Also a very odd UI behaviour: When selecting the second WH, no flag appears to be set on soldiers, once setting the collect flag on one soldier type the other soldier types get the collect flag.

**Comment by Flamefire** [comment] 2016-01-31 20:49
There is a visual bug with the settings for figures. #382
The icon might not be shown when you open the window. It is corrected when you change the setting (might look as nothing happened in your case) 
Of you still think it does not work then please attach a replay
