### ISSUE TITLE
Bug detected (GF: 211804)

### ISSUE THREAD

**Issue by A1uca2d** [Return-To-The-Roots/s25client#641] opened 2017-06-17 09:42 UTC
I have a Bug in a Game:
`WARNING: Bug detected (GF: 211804). Please report this with the savegame and replay. noShip::StartDrivingToHarborPlace: Schiff hat keinen Weg gefunden! player  state 11 pos 75,366 goal coastal 497,192 goal-id 36 goalpos 497,191`

**Comment by Spikeone** [comment] 2017-06-17 09:44
Hi, thanks for reporting.
Which map you were playing on and what game version did you use (stable / nightly)?

**Comment by A1uca2d** [comment] 2017-06-17 14:38
Hey,

I Use auctually the Version: v20170309-bf9fcc6 ands the map was a selfe made (by your mapgen.) I have uploaded the map here: [https://nextarp.my-router.de/index.php/s/KDhAWVYgeGc7vmS](url)

**Comment by Spikeone** [comment] 2017-06-17 19:57
maybe same as #640

**Comment by stefson** [comment] 2017-06-29 05:59
#640 is propably related, yes. Are these map bugs, so that the map generator made a mistake?

**Comment by Spikeone** [comment] 2017-06-29 06:14
Or the generator generates a special constellation which should work but doesn't. 

Im going to take a look at the map. 

Did this  happen when sending exploration expeditions?

**Comment by stefson** [comment] 2017-06-29 06:24
On the map I used it happend when I wanted to built more buildings on the outpost in the very far east of Russia, therefore building material was needed and never got transported. But please have a look at the replay, it is attached in #641

**Comment by Flamefire** [comment] 2017-07-05 06:40
Duplicate of #640. Same issue

**Closed by Flamefire** 2017-07-05 06:40 UTC
Labels: duplicate
