### ISSUE TITLE
[Addon] No Demolition Mode

### ISSUE THREAD

**Issue by Vinkdicator** [Return-To-The-Roots/s25client#1148] opened 2019-12-31 02:19 UTC
Currently, whenever you occupy an enemy military building, all the items on the paths, the paths themselves, workers and civil buildings are destroyed. I would really enjoy an addon where they are simply converted to your faction. It seems more realistic too. (Not that Settlers needs to be realistic)
If a catapult or the player destroys the military building they could go to a dummy faction until someone claims land over them again.

**Comment by Spikeone** [comment] 2019-12-31 11:42
Although the issue is in german, this is a duplicate of #121

**Closed by Spikeone** 2019-12-31 11:42 UTC
Labels: addon, duplicate
