### ISSUE TITLE
User interface boxes are not drawn in place anymore

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#860] opened 2018-08-06 18:51 UTC
I marked it with red, so that it can be identified easier. Those boxes should be a little bit bigger and the background should not shine through: 

![boxes](https://user-images.githubusercontent.com/14232936/43735103-157280b4-99ba-11e8-8efe-d199c8a97692.png)

**Comment by Flamefire** [comment] 2018-08-11 12:13
Seems to be fixed in latest nightly, can't reproduce on windows at least. Can you try with latest nightly please?

**Comment by stefson** [comment] 2018-08-11 12:31
You're right. This checkout is from your modernOGL branch, I totally forgot to change back to the master branch.

**Comment by Flamefire** [comment] 2018-08-11 12:33
Thanks, will watch out for this issue.

**Closed by Flamefire** 2018-08-11 12:33 UTC
