### ISSUE TITLE
high cpu usage while saving the game (regression)

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#744] opened 2017-11-11 06:54 UTC
Saving the game, both via the autosave function and via the normal file dialog, uses 100% cpu on one core for at least 10 seconds on my system. There is no backtrace for this or error in the logs, I am at current 02770d57f2ae8432139edc3e6f00cc3a1a54c723

**Comment by stefson** [comment] 2017-11-11 07:13
The same happens if you want to access the replay section of the game menu. No hard crash or segfault though, but still waiting to load the file chooser dialog for two minutes now.

**Comment by stefson** [comment] 2017-11-11 08:06
Turns out there is no savegame present in the folder, is that possible?

**Comment by Flamefire** [comment] 2017-11-11 08:31
Will double check this. Could you send me your replay folder?
And yes I changed the file formats to be more effective. Therefore old files can't be loaded anymore

**Comment by stefson** [comment] 2017-11-11 08:59
Sure, here is the complete folder: [REPLAYS.zip](https://github.com/Return-To-The-Roots/s25client/files/1463574/REPLAYS.zip) 

It seems as if the savegames are stored in the wrong place, in ~/.s25rttr/ , instead of in ~/.s25rttr/SAVE/ , and that the game cannot find them anymore if you want to load a saved game. If copied over by hand they seem to load just fine.

**Comment by Flamefire** [comment] 2017-11-11 17:00
Fixed the savegame path. However can't reproduce the 2 minutes for the replay even in VS debug mode. In debug builds it is expected to take a bit for saving loading due to missing inline.

**Comment by stefson** [comment] 2017-11-11 22:10
It works for small maps now, but the bigger the map the worse it gets. The process uses 100% on one core, and it takes several minutes for bit bigger maps. On huge maps it is likely never going to finish. 

However, loading a savegome works fine now with #748 merged.

**Comment by Flamefire** [comment] 2017-11-11 23:45
100% is ok. It uses all there is to process the save.
It shouldn't take that long though
What do you do? Load or save? Can you post the file? Don't have it here. It's just 5s or so

**Comment by stefson** [comment] 2017-11-12 10:48
Tried to stop the time by hand, but it turns out that the binary hangs now without any segfault or the like, more in an infinity loop or so? The s25client uses 100% cpu and still claims to be busy with saving the savegame while 10 minutes have passed, and the savegame file which I am going to attach is present in the filesystem: [benchmark.sav.zip](https://github.com/Return-To-The-Roots/s25client/files/1464528/benchmark.sav.zip) or to be more precise: the file has been saved, but the thread is still at 100% cpu. 

If I want to go back, after having killed the binary and reloaded the game, the whole file picker dialog never makes it but instead stalls in a sort of infinitv loop (?), again. 

Now, while I tried to find the map which I used to add it to the archive, if you shouldn't have it locally, I noticed, that there is another .sav file with the same name present under MAPS/ , same md5sum, only timestamp differs for 2 minutes. Which is approximatley the amount of time it took to save the game. So this one was a sucessfully saved game which didn't kill the binary and which loaded fine after a restart. Here it is all zipped up into one archive, plus the logs if they are of any use: [SAVE.zip](https://github.com/Return-To-The-Roots/s25client/files/1464536/SAVE.zip)

To be continued.

**Comment by Flamefire** [comment] 2017-11-12 12:28
I think I know the reason: I switched the internal buffer to a boost::vector with default-init as a replacement to a custom uninitialized-vector. However it has a problem: While `reserve` of the custom class reserved more elements than requested to be efficient, the boost class does not do this.
I'll change this to do it manually.

**Comment by Flamefire** [comment] 2017-11-13 10:06
Fixed with c800d51

**Closed by Flamefire** 2017-11-13 10:06 UTC
