### ISSUE TITLE
libGL error: No matching fbConfigs or visuals found

### ISSUE THREAD

**Issue by ubmarco** [Return-To-The-Roots/s25client#1192] opened 2020-02-18 11:55 UTC
Hi!
Thanks for this great game.
I'm on Manjaro XFCE. I have an old nVidia GeForce GTS 250 graphics card.
When using the `video-linux` driver in the Manjaro Settings Manager which installs the Nouveau driver, the game starts and works flawless. However when I use video-nvidia-340xx I get the error:
```
marco@keks ~ rttr.sh
Return To The Roots v20200212-b7f38122f97f08a21c0b55b673d8d06c113a5639
Compiled with GNU C++ version 9.2.0 for linux 64 Bit

Starting in /usr


WARNING: Your application version has changed - please recheck your settings!

Searching for drivers in /usr/lib/s25rttr/driver/video
2 video drivers found!
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  107
  Current serial number in output stream:  106
```
This might be problem with nvidia driver and my old GTS 250 card, but maybe you have a hint how to fix this.

On the page https://wiki.archlinux.org/index.php/NVIDIA I see in section **Unsupported drivers**:
> For GeForce 2/3/4 MX/Ti series cards [NV11, NV17-NV28], install the nvidia-96xx-dkms (AUR) package. Last supported Xorg version is 1.12.

I however have `X.Org X Server 1.20.7`. Can anyone confirm that's my problem?
Manjaro installs the following modules:
```
lib32-nvidia-340xx-utils 340.108-1
linux53-nvidia-340xx 340.108-1
linux54-nvidia-340xx 340.108-13
mhwd-nvidia-340xx 340.108-1
mhwd-nvidia-390xx 390.132-1
mhwd-nvidia-418xx 418.113-1
mhwd-nvidia-430xx 430.64-1.0
mhwd-nvidia-435xx 435.21-1.0
mhwd-nvidia-440xx 440.59-1
nvidia-340xx-utils 340.108-1
```

I also checked if I can run other 3D programs like `glxgears` and `glmark2`. Both run flawless using the nvidia driver.
```
marco@keks ~ glmark2
=======================================================
    glmark2 2014.03
=======================================================
    OpenGL Information
    GL_VENDOR:     NVIDIA Corporation
    GL_RENDERER:   GeForce GTS 250/PCIe/SSE2
    GL_VERSION:    3.3.0 NVIDIA 340.108
=======================================================
[build] use-vbo=false: FPS: 1907 FrameTime: 0.524 ms
[build] use-vbo=true: FPS: 2604 FrameTime: 0.384 ms
...
```

**Comment by Flamefire** [comment] 2020-02-18 13:45
Try to use the SDL2 driver for RttR by modifying the config accordingly or by deleting the SDL driver and NOT running the updater (`rttr.sh --noupdate` IIRC, check the file to be sure)

**Comment by ubmarco** [comment] 2020-02-18 19:45
I hope I understood this correctly. You mean I should use SDL2 instead of SDL right? I modified the directory to this:
```
marco@keks $ tree /usr/lib/s25rttr/driver/
/usr/lib/s25rttr/driver/
├── audio
│   └── libaudioSDL.so
├── libvideoSDL.so
└── video
    └── libvideoSDL2.so
```
So I moved the file `libvideoSDL.so` one folder up.
Then I get the same result, just with one video driver less.
```
marco@keks ~ rttr.sh --noupdate
Return To The Roots v20200212-b7f38122f97f08a21c0b55b673d8d06c113a5639
Compiled with GNU C++ version 9.2.0 for linux 64 Bit

Starting in /usr


WARNING: Your application version has changed - please recheck your settings!

Searching for drivers in /usr/lib/s25rttr/driver/video
1 video drivers found!
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  107
  Current serial number in output stream:  106
```
Any hint to which config I should modify as per your first suggestion?

**Comment by Flow86** [comment] 2020-02-19 08:55
Hi,

> libGL error: failed to load driver: swrast

comes from a not installed software rendering driver or a missing symbol. (this is common for the nvidia driver f***ing up the rendering sometimes.

try this:

# LIBGL_DEBUG=verbose rttr.sh --no-update

perhaps we can find out which library he can't load.

**Comment by stefson** [comment] 2020-02-19 18:03
this is more or less a duplicate of an older issue with debian10 on my rpi2. 

for reference: https://github.com/Return-To-The-Roots/s25client/issues/1101

**Comment by ubmarco** [comment] 2020-02-20 11:30
Verbose output:
```
marco@keks $ LIBGL_DEBUG=verbose rttr.sh --no-update
Return To The Roots v20200212-b7f38122f97f08a21c0b55b673d8d06c113a5639
Compiled with GNU C++ version 9.2.0 for linux 64 Bit

Starting in /usr


WARNING: Your application version has changed - please recheck your settings!

Searching for drivers in /usr/lib/s25rttr/driver/video
2 video drivers found!
libGL: screen 0 does not appear to be DRI2 capable
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/marco/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/marco/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  107
  Current serial number in output stream:  106
```
I'm not sure it's the same issue as #1101 because I'm missing the lines
```
Loaded video driver "(SDL) OpenGL via SDL-Library"
OpenGL 3.1 supported
```
However `s25edit` also works perfectly fine for me.
Here's an [strace](https://github.com/Return-To-The-Roots/s25client/files/4230444/strace.log).

**Comment by Flow86** [comment] 2020-02-20 12:01
Hi, thats only the strace of the shell script. try using `strace -f` to follow child processes

**Comment by ubmarco** [comment] 2020-02-20 12:56
Thanks for that hint. [Here](https://github.com/Return-To-The-Roots/s25client/files/4230767/strace.log) is the output of
`LIBGL_DEBUG=verbose strace -f rttr.sh --no-update &> strace.log`

**Comment by ubmarco** [comment] 2020-02-20 13:03
In the strace I see that it's looking for libGL.so in the following locations
```
[pid  3337] openat(AT_FDCWD, "/usr/lib/s25rttr/driver/video/libGL.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  3337] openat(AT_FDCWD, "/usr/bin/libGL.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  3337] openat(AT_FDCWD, "/usr/bin/../lib/libGL.so.1", O_RDONLY|O_CLOEXEC) = 7
```
I guess it will use the file `/usr/lib/libGL.so.1` as it's the only existing of the 3. This is a list of all libGL shared objects I have:
```
marco@keks ~ sudo find /usr -iname "*libGL.so*" -exec ls -l -- {} +
lrwxrwxrwx 1 root root      10  9. Jan 15:08 /usr/lib32/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      14  9. Jan 15:08 /usr/lib32/libGL.so.1 -> libGL.so.1.7.0
-rwxr-xr-x 1 root root  435384  9. Jan 15:08 /usr/lib32/libGL.so.1.7.0
lrwxrwxrwx 1 root root      10 26. Dez 10:33 /usr/lib32/nvidia/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      16 26. Dez 10:33 /usr/lib32/nvidia/libGL.so.1 -> libGL.so.340.108
-rwxr-xr-x 1 root root 1075136 26. Dez 10:33 /usr/lib32/nvidia/libGL.so.340.108
lrwxrwxrwx 1 root root      10  6. Jan 15:41 /usr/lib/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      14  6. Jan 15:41 /usr/lib/libGL.so.1 -> libGL.so.1.7.0
-rwxr-xr-x 1 root root  538368  6. Jan 15:41 /usr/lib/libGL.so.1.7.0
lrwxrwxrwx 1 root root      10 26. Dez 10:17 /usr/lib/nvidia/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      16 26. Dez 10:17 /usr/lib/nvidia/libGL.so.1 -> libGL.so.340.108
-rwxr-xr-x 1 root root 1267800 26. Dez 10:17 /usr/lib/nvidia/libGL.so.340.108
```
This means it will finally use `/usr/lib/libGL.so.1.7.0`. Shall I try to symlink it to `/usr/lib/nvidia/libGL.so.340.108`?

**Comment by ubmarco** [comment] 2020-02-20 13:09
Yep, that fixes the problem.
```
marco@keks /usr/lib > sudo rm libGL.so.1
marco@keks /usr/lib > sudo ln -s /usr/lib/nvidia/libGL.so.1 libGL.so.1
marco@keks /usr/lib > sudo find /usr -iname "*libGL.so*" -exec ls -l -- {} +
lrwxrwxrwx 1 root root      10  9. Jan 15:08 /usr/lib32/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      14  9. Jan 15:08 /usr/lib32/libGL.so.1 -> libGL.so.1.7.0
-rwxr-xr-x 1 root root  435384  9. Jan 15:08 /usr/lib32/libGL.so.1.7.0
lrwxrwxrwx 1 root root      10 26. Dez 10:33 /usr/lib32/nvidia/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      16 26. Dez 10:33 /usr/lib32/nvidia/libGL.so.1 -> libGL.so.340.108
-rwxr-xr-x 1 root root 1075136 26. Dez 10:33 /usr/lib32/nvidia/libGL.so.340.108
lrwxrwxrwx 1 root root      10  6. Jan 15:41 /usr/lib/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      26 20. Feb 14:05 /usr/lib/libGL.so.1 -> /usr/lib/nvidia/libGL.so.1
-rwxr-xr-x 1 root root  538368  6. Jan 15:41 /usr/lib/libGL.so.1.7.0
lrwxrwxrwx 1 root root      10 26. Dez 10:17 /usr/lib/nvidia/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      16 26. Dez 10:17 /usr/lib/nvidia/libGL.so.1 -> libGL.so.340.108
-rwxr-xr-x 1 root root 1267800 26. Dez 10:17 /usr/lib/nvidia/libGL.so.340.108

marco@keks /usr/lib > rttr.sh
Return To The Roots v20200212-b7f38122f97f08a21c0b55b673d8d06c113a5639
Compiled with GNU C++ version 9.2.0 for linux 64 Bit

Starting in /usr


WARNING: Your application version has changed - please recheck your settings!

Searching for drivers in /usr/lib/s25rttr/driver/video
2 video drivers found!
Loaded video driver "(SDL2) OpenGL via SDL2-Library"
OpenGL 3.3 supported
Searching for drivers in /usr/lib/s25rttr/driver/audio
1 audio drivers found!
Loaded audio driver "(SDL) Audio via SDL_mixer-Library"

Starting the game
Loading "/usr/share/s25rttr/RTTR/splash.bmp": done in 16ms
Loading "/usr/share/s25rttr/S2/GFX/PALETTE/PAL5.BBM": done in 1ms
...
```
So what's the source of the problem? Is it s25client not looking in the right location or is it the nvidia driver not correctly symlinking `/usr/lib/libGL.so`? Or is it Manjaro not installing the right symlink?

**Comment by Flow86** [comment] 2020-02-20 13:41
> or is it the nvidia driver not correctly symlinking /usr/lib/libGL.so? Or is it Manjaro not installing the right symlink?

I think one of these two or perhaps both

**Closed** 2020-02-22 21:20 UTC
