### ISSUE TITLE
BUG: lua does not getfound in contrib correctly

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#838] opened 2018-05-11 20:05 UTC
on all platforms, this error occurs on a fresh checkout:

```
[windows.i386] CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
[windows.i386]   Could NOT find LUA (missing: LUA_INCLUDE_DIR LUA_LIBRARY) (Required is
[windows.i386]   exact version "5.2.1")
[windows.i386] Call Stack (most recent call first):
[windows.i386]   /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
[windows.i386]   libutil/cmake/Modules/FindLUA.cmake:139 (find_package_handle_standard_args)
[windows.i386]   src/libGamedata/CMakeLists.txt:41 (find_package)
```

I also tried to set LUA_DIR manually (see f8d1e57e09c4012820266b039df4bc91d8e33d13) but still no change

**Comment by Shawn8901** [comment] 2018-05-11 21:36
not 100% sure, but should be related to #832.

**Comment by Flamefire** [comment] 2018-05-12 15:56
Yes I'm working on it. However there is a CMake-Bug which prevents from #832 being merged. I'm now testing the CMake 3.x FindLua (official one, so we don't have to maintain it) and will push that once it built.

The commit f8d1e57 can be reverted, the new LUA module only looks into the environment variable and the updated CMakeLists will set that correctly.

**Comment by Flow86** [comment] 2018-05-12 16:52
the problem is that cmake searches in LUA_DIR/ + LUA_DIR/include for the lua.h - it will never search in LUA_DIR/../include

one possibility is to copy from the "common" lua include inside the architecture directories. alternative is to add LUA_DIR/../include to the hints

**Comment by Flamefire** [comment] 2018-05-12 16:57
Nope. Won't work. LUA_DIR is meant to tell CMake where to find a `LuaConfig.cmake`. The problem is that LUA_DIR is not a prefix, so subfolders like include or lib are not searched. Previously I fixed that already (FindLUA.cmake [uppercase]) but CMake had a bug. So I have fixed that in #832 by using `Env{LUA_DIR}` and `CMAKE_PREFIX_PATH` with the upstream `FindLua.cmake`. I
On my local Linux it works. Waiting for travis.

The modification of FindLua is not required and might cause problems later on...

**Comment by Flow86** [comment] 2018-05-12 17:06
here it does not work

**Comment by Flamefire** [comment] 2018-05-12 17:08
If you revert your commits (maybe all down to 5170cabfd990747b43ac609bfabc1006a40b5bd5) #832 can be applied. That should work (tested)

**Comment by Flow86** [comment] 2018-05-12 17:11
reverted - you still have to rebase (submodules ...)

**Closed** 2018-05-12 17:12 UTC
Labels: bug, cmake
