### ISSUE TITLE
Nightly build windows i386 not working

### ISSUE THREAD

**Issue by 0Jmaster0** [Return-To-The-Roots/s25client#615] opened 2016-12-20 22:08 UTC
All available builds(from 20160903) for Windows i386 crashes immediately after press "Start game", returning text "RTTR crashed". Debug information was sent
![screenshot](https://cloud.githubusercontent.com/assets/24686124/21369776/92734c30-c719-11e6-8df3-fa108f4d2496.jpg)

Tried on 3 different computers, with windows 7(one of them x64, x86_64 version works well).

**Comment by Flow86** [comment] 2016-12-20 22:12
confirmed +1

**Comment by Flow86** [comment] 2016-12-23 21:58
Hi,

I still can't fix the bug, but I was able to reproduce and isolate it.

Change "Graphics Driver" in "Settings" -> "Graphics" to "SDL". 
Restart the game and it works.

It seems the WinAPI-Driver has some weird problem

**Comment by 0Jmaster0** [comment] 2016-12-24 12:28
Thank you, it worked :) Now I can play version newer than the stable one :)

**Comment by Spikeone** [comment] 2018-11-03 13:03
Looks like this is fixed? Closing this bug for now.

**Closed by Spikeone** 2018-11-03 13:03 UTC
Labels: bug, crash
