### ISSUE TITLE
Jump to next same crashed the game

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1105] opened 2019-08-21 21:22 UTC
I used the "Jump to next same" feature. Sadly the game crashed on the second click. Replay should be sent (at least console told so).

**Comment by Flamefire** [comment] 2019-08-22 06:46
I just tried in a new game and could not reproduce. Can you send the replay via github and do you remember what you clicked? Which building? Any other open windows?

**Comment by Spikeone** [comment] 2019-08-23 08:18
You can "watch" the crash here: https://youtu.be/wKK2y-m_gMs?t=5930

I did some further testing and could reproduce it (at least with the replay)

Looks like the game crashes if you "jump to same" and the wares window is already opened. In my testing I just searched for some storehouses, opened clicked on them opening the wares window (until I got 5) and then hit "jump to next same" and the game crashed. 

[2019-08-21_21-41-46.zip](https://github.com/Return-To-The-Roots/s25client/files/3533497/2019-08-21_21-41-46.zip)

**Comment by Flamefire** [comment] 2019-08-23 12:49
Ah nice, found it. There is even a comment: `todo: only open if it isnt already open`. The problem: When it tries to show a window that is already open then it closes both windows and returns NULL which is accessed in this case causing the crash.

Easiest would be to simply close the new window and return the other or close the old and return the new (as done with help windows) but I guess there was a reason to make "open again = close" the behavior?

**Comment by Flamefire** [comment] 2019-08-23 13:35
I think we should simply close the old window and let the new one open. Having `WINDOWMANAGER.Show(...)` close a window is unexpected. And does anyone really rely on this toggling? E.g. clicking on a building opens the window, clicking the building again closes it. IMO it would be better to simply reopen it which moves it to the foreground. This is consistent with e.g. the place-flag/building window. @Spikeone what do you say? I think this would be a slight derivation from the original  but I'm not even 100% sure it was that way there.

**Comment by Spikeone** [comment] 2019-08-23 21:34
Well, I'm not really using this feature. Guess I only used it cause I wat a little... drunk ;)

Anyway, on one hand it sounds logical, that the the window stays at the same position (thus reopening the open window at the same position)
On the the other hand the function is only meant to "jump to next same" so - why should it move my windows around? They should be kept where they are and just gain focus.

Hard decision actually which one is the right behavior. As opening the same window twice seems no good option as well, I'd rather vote for... no idea. Just pick one, some people will dislike it other will not I guess.

**Comment by Flamefire** [comment] 2019-08-24 10:38
>  Derivation from the original? 

I mean: Fix the problem at its root and do this for ALL windows. In the original clicking the "map" button opened the map window. Clicking it again closed it.    
The reworked version with this problem fixed would reopen the window on the 2nd click instead of closing it.

Alternatively we could search for all instances where a "toggle behavior" is wanted and explicitly add checks of whether to open or close the window. Obviously this is more work...

**Comment by Spikeone** [comment] 2019-08-24 12:41
Oh, yeah.

Sadly it's no original behavior that a click does 2 actions (jump to somewhere and open a window).

I guess just fixing the crash will suffice, not sure what people use this for at all.
Maybe excluding buildings you have the window opened for is a good way for both use cases. Not sure if this means even more work.
Because: why should I search for abuilding I have the window opened for? I got the window with a jump to button so... No need to find it again.

**Closed** 2019-10-11 15:40 UTC
