### ISSUE TITLE
Seefahrt unbrauchbar

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#278] opened 2015-09-25 22:00 UTC
Heute habe ich einmal mehr an die Seefahrt gewagt - leider ist diese wieder komplett nutzlos.
Wenn man Gebäude auf anderen Inseln fertig stellt so tritt das schöne Problem auf, dass nur Siedler die bereits auf der Insel sind korrekt verwendet werden, sollte neue Siedler benötigt sein, so werden diese - so irgendwie - immerhin geholt aber sie Besetzen Gebäude nie.
Ich hatte so einen Spähturm der zwar im Hafen einen Späher hatte (vom Schiff gebracht) aber nicht den Spähturm besetzt.
Bei der Festung ähnliches aber grausameres Spiel: Ich hatte bereits Soldaten, 1 frei und 16 in Reserve, der eine hat die Festung besetzt, die anderen 16 aus der Reserve genommen und es geschieht: nichts. Normalerweise müssten die Soldaten nun das Gebäude besetzen (hatte keine anderen freien Soldaten). Neu verbinden der Wege hat auch nicht geholfen.
Der Steinmetz lief auf 50% und wurde von Zeit zu Zeit als besetzt angezeigt - danach wieder als unbesetzt.

Ich würde darum bitten, dass entweder "fixes" wenigstens grob getestet werden oder es irgendwo wenigstens eine Liste gibt was alles getestet werden müsste - so ist es sehr deprimierend wenn man Sachen 10x testet weil man nie weiß was gerade nicht mehr funktionieren könnte in den Versionen...

**Comment by jhkl** [comment] 2015-09-25 23:06
Update for figures was missing, should be fixed with fc220f2f74a786bea75ee43ecd1e62fde1d42dfe

**Comment by jhkl** [comment] 2015-09-25 23:07
Tests for these kinds of changes can easily be done by replaying a replay! Should work before & after.

**Closed by jhkl** 2015-09-25 23:06 UTC

**Comment by Flamefire** [comment] 2015-09-26 10:36
RTTR is to complex to run all these tests. What we need would be a "ghost" player or so, which uses all features in as few time as possible. So one can use this to create a replay before changes and run this after the changes. The problem is: This is hard. I tested the changes I have made with a replay and by playing manually for a couple of minutes as well as by starting a KI game and run it for 10k GFs. You can't catch everything by hand...

**Comment by Spikeone** [comment] 2015-09-26 18:41
I totally agree with you about that - but when seafaring is changed it's quite easy to test basic things like: do sea attacks work? Are wares and settlers transported? Are all expedition types working?
If it's not done by a dev, I'd be happy to have notes about that somewhere...

**Comment by Flamefire** [comment] 2015-09-26 19:35
Well only if you expect that a change will break seafaring. The change in question was pretty general and how would I have known that it will only break seafaring but work in all other cases (that were tested)? That is why it is a nightly. It is the current development build. Nothing stable. We need users to test all features. This is much faster than having to check everything manually on every change...

**Comment by Spikeone** [comment] 2015-09-26 21:28
Yeah, and thats why I'm here as well, to be a testing user that we can track down bugs as fast as possible...
It's just an offer, that I would test a bit more focused but, I guess you are not interested then.

**Comment by Flamefire** [comment] 2015-09-27 02:41
I am interested. Please don't get me wrong here.I just don't know how to do it in a reasonable manner. I suggested to jh to use a "bot" player that uses all features of rttr. This can be used to create replays which can then be tested after non-gamechanging changes like refactoring. This would be an option... Any other ideas?

**Comment by Spikeone** [comment] 2015-09-27 09:15
Well, I have no idea what the code looks like, thats why I could totally agree with being a tester, just the same I did when Maqs fixed things. He knew what may be affected so he just told me and I played a bit and tested as far as I could imagine situations.
You are normally right about "users should test nightlys" but... how many user will end up here reporting a bug? Sadly not much. Also it's quite a bad joke to tell people "yeah well use the stable version" because in fact, it's less stable and has less features.
Maybe we should add more stable versions like: X.[featurenumber].[fixnumber] so for examble 0.8 got I guess 9 new features and... lets say 40 fixes so we could have a stable 0.8.9.40 - that way we could say "okay, thats currently bugged, use the latest stable" and we also could really close features as the issues should be only closed after it is included in a stable version, that way we wouldn't have so much broken addons (metalworker, improved alliances, trade).
So thats just what I think, I do not expect a dev to fully test what he did (just obvious things) and thats why we got testers, well me.

**Comment by Flamefire** [comment] 2015-09-27 10:49
Yes and you are a very good tester. What you report is nice and very helpful so it can be fixed fast.

And yes I agree with the more versions. And this is what 0.8.3 is for: Fixing all the currently known bugs. I'm not implementing any features. Just fixing bugs and "repairing" the code so bugs are less likely or more obvious (metalworker e.g. where an assertion was thrown instead of simply wrong behaviour) So after all issues (bugs) for 0.8.3 are closed we have a real stable version again. I'd maybe call it 0.9 instead as it is a huge step forwards compared to the last version and user should see that...
