### ISSUE TITLE
Game does not start on MacOS Ventura: "rttr.terminal" can't be opened because 'null' is not allowed to open documents in Terminal 

### ISSUE THREAD

**Issue by FixedSpeed** [Return-To-The-Roots/s25client#1543] opened 2022-12-19 20:38 UTC
When running the latest version 20220922 rev. 0537322 on MacOS Ventura 13.0.1 (MacBook Pro i5) the following error message is shown:

![Screenshot_2022-12-07_at_21 35 09](https://user-images.githubusercontent.com/40797859/208516468-ac0d0f7d-31ff-4154-82f0-f32b6295a30b.png)
There is description on why this happens, the game does not start.

**Comment by FixedSpeed** [comment] 2022-12-19 20:41
I have checked out the master and the local build failed because of the use of the sprintf() function. Apparently the use of snprintf() is needed. After replacing sprintf() occurences, the build was completed and the game started without issues.

I will create a pull request for this change.

**Comment by FixedSpeed** [comment] 2023-01-17 12:36
@Flamefire As you were expecting, the latest nightly build (which included the snprint() replacement) didn't fix this issue.

Can you give me some pointers on where to look for regarding this rttr.terminal error maybe ? Have you seen this error before on macOS ?

**Comment by FixedSpeed** [comment] 2023-01-17 12:55
Apparently the games does load when the s25client is run directly from the macOS package (Contents/MacOS/).

**Comment by mtoensing** [comment] 2023-02-20 21:54
Same problem here!

**Comment by mtoensing** [comment] 2023-02-21 09:49
Maybe a problem or challange with the security system of macOS Ventura. https://github.com/facebook/react-native/issues/35726

**Comment by mtoensing** [comment] 2023-02-21 09:55
More info about the know bug from Apple: https://developer.apple.com/forums/thread/723842

**Comment by mtoensing** [comment] 2023-03-01 08:30
It seems like this is not a bug on Apples end, but a security measure. So this has to be fixed in RTTR. My idea would be instead of one launcher it would be more compatible to use 3 .app files for updater, client and editor. At least for macOS Ventura and up.

**Comment by Flamefire** [comment] 2023-03-01 15:59
Currently the design is that the updater runs prior to starting the client to keep it up to date. Having 3 .app files might not ensure this and hence require manual updating.

Unfortunately I don't know enough about macOS to fix this, so someone with expertise there and a system to test this on would be welcome.

**Comment by mtoensing** [comment] 2023-03-01 16:00
I can offer to test. I started s25clienr directly and never used the updater

**Comment by FixedSpeed** [comment] 2023-03-01 16:15
Same here, happy to test!

And, not to jump to conclusions, but maybe we think of different ways to keep the client up to date. For example: offer the option in the main menu, maybe with a notification of a new version available.

**Comment by mtoensing** [comment] 2023-03-01 16:25
Would be great. Because on Mac you will most likely update to Ventura or at least to Big Sur. It is not like Windows where you can stay on W10 for eternity.

**Comment by mtoensing** [comment] 2023-03-01 16:31
And getting rid of the .app approach would be better for everyone. Because the s2. folder inside the .app "folder" is something which not everyone will understand that you have to open it with "show contents" to put the GFX and DATA folder inside that. Normally you don't open these .app folders. 

Separate executables would be great along with s2 folder on the same depth. Or if you use .app folders the data goes to ~/Documents/RTTR/s2 or something.

**Comment by Spikeone** [comment] 2023-03-01 17:14
@Flamefire on windows we don't have that design, you'd have to run the rttr.bat (on linux I guess rttr.sh?) so I'm suprised that the mac client always updates (you have no chance to use a specific version then, do you?)

**Comment by mtoensing** [comment] 2023-03-01 17:19
Okay, in that case: why not just a single rttr.sh file for Mac that points to he binary alongside the s2 folder?

**Comment by mtoensing** [comment] 2023-03-01 21:44
I just looked at the windows and linux file structures of RTTR:

<img width="1167" alt="Screenshot 2023-03-01 at 22 42 43" src="https://user-images.githubusercontent.com/136737/222271564-5f1743d3-cead-40a5-91dd-e5ce6e8a493d.png">

I don't know who came up with the idea to bundle the mac version as the .app file. Just distribute it like windows and linux. Everyone will easier understand where to put the original files and no more problems with macOS security measures in the future.

**Comment by FixedSpeed** [comment] 2023-03-03 06:10
Agree, that was my thought as well. Sounds much more clear and simple.

**Comment by mtoensing** [comment] 2023-03-10 16:58
Seit dem letzten Update von macOS Ventura startet das Spiel ganz normal bei mir.

**Comment by FixedSpeed** [comment] 2023-03-13 08:48
> Seit dem letzten Update von macOS Ventura startet das Spiel ganz normal bei mir.

Hi, on which version of macOS Ventura are you currently ? Did you use the latest nightly build 20230312 (40018c4) for Mac ?

I'm on 13.2.1 (22D68).

**Comment by mtoensing** [comment] 2023-03-13 08:52
Stable non-beta. I just pressed update

**Comment by mtoensing** [comment] 2023-03-15 08:15
I was wrong. I played around with the scripts and Info.plist and made it work somehow. When I download the regular version, it still crashes with the error

**Comment by MLipfert1** [comment] 2023-04-02 16:20
This issue seems to be fixed in Ventura 13.3.

**Comment by mtoensing** [comment] 2023-04-09 12:56
This issue can be closed, but there is a new issue #1573 with macOS if someone discovers this by searching google.

**Comment by Spikeone** [comment] 2023-04-09 14:08
closing as requested, thanks for keeping this updated @mtoensing :)

**Closed by Spikeone** 2023-04-09 14:08 UTC
