### ISSUE TITLE
Seafaring not working correctly on anywayz

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#391] opened 2016-02-17 10:27 UTC
I was testing the new anywayz map. 

two issues appeared. First of all, starting at around 73000, the AI takes over the control. I will attach the replay
[2016-02-17_10-15-29.rpl_res.zip](https://github.com/Return-To-The-Roots/s25client/files/134039/2016-02-17_10-15-29.rpl_res.zip) Does anyone need a savegame as well? 

The other issue is, that the ships which my first ship builder builds have not made it to the harbour to start the expedition I scheduled. For that, I had to build a new ship builder. Later on, I couldn't start a new expedition, but that was I guess beyond the point where the AI took over the controll.

**Comment by Flamefire** [comment] 2016-02-17 12:43
What do you mean by "ai took over control"? An AI was controlling your units? Building for you? 
And why could you not start an expedition later on? What was happening?

**Comment by stefson** [comment] 2016-02-17 17:15
An AI took over the controll and building. You can see it in the replay at around 73.000 where the AI builds a lot of buildings very fast in those areas I have left open. 

I built a harbour and a shipbuilder, but couldn't start the Expedition as the two ships he build are somehow stuck on the beach. I had to add a second shipbuilder, from where the ship than started with the expedition. However, a second expedition wasn't possible anymore, but that was beyond the overtake of the AI if I remember correctly. 

Do you need the save game?

**Comment by Flamefire** [comment] 2016-02-17 17:18
Did you use a debug build? There you can press F10 to have an AI play for you. Otherwise this should be impossible... 
Will look into the expedition issue.

**Comment by Flamefire** [comment] 2016-02-17 17:18
And yes just attach the save game. Just in case...

**Comment by stefson** [comment] 2016-02-17 17:31
Yes, I am using a debug build. Maybe I hit F10 by accident, will hitting it another time disable the AI playing for me? So yeah, the ships are build but stuck on the beach half way between the first shipbuilder and the harbour. 

[Anywayz (Automatisches Speichern).sav.zip](https://github.com/Return-To-The-Roots/s25client/files/134821/Anywayz.Automatisches.Speichern.sav.zip)

[test.sav.zip](https://github.com/Return-To-The-Roots/s25client/files/134838/test.sav.zip)

**Comment by Flamefire** [comment] 2016-02-18 15:52
Yes this is right. This feature is good for testing...

We'll look into the ships issue. @jhkl already mentioned something about problems with ships on anywayz to @Spikeone. Maybe they have some information?

**Comment by Spikeone** [comment] 2016-02-20 22:30
Gonna check the map - should work as intended (if anything works as known)

**Comment by Flamefire** [comment] 2016-02-22 09:29
Can you describe exactly what is "allowed area" and what isn't?
What is the "unshippable" water? And yes I guess this is the problem as the algorithm only checks for water ATM

**Comment by Spikeone** [comment] 2016-02-22 15:15
Well, there are small islands for every player. If you have a look at the preview map or my screenshot with red and green circled water.
Those islands are surrounded by unshipable water - a ship built inside that area works as known, a ship built outside won't be called by the harbor (works as designed).
As this isn't visible for most players (most don't even know that additional water type) this behavior looks like a bug but it isn't.

This is just a design fail which I'm gonna fix today.

**Comment by Spikeone** [comment] 2016-02-28 14:09
Improved map (and fixed missing resources)

http://www.rfmonline.de/rttr/spike/1-anywayz.zip

**Comment by Flamefire** [comment] 2016-02-28 17:19
Added a change so that the water becomes visible.
![water](https://cloud.githubusercontent.com/assets/309017/13380609/b6a08bec-de47-11e5-8bdc-fecc0c3ab52b.png)

**Comment by Flamefire** [comment] 2016-02-28 17:52
Next: Seas will be correctly calculated: 
![seas](https://cloud.githubusercontent.com/assets/309017/13380835/7728f79c-de4c-11e5-81c0-80cc6c0330d2.png)

**Comment by Spikeone** [comment] 2016-02-28 21:30
Uhm no please don't - that water is used to actually build blockades which you can't see

**Comment by Flamefire** [comment] 2016-02-29 06:48
I don't agree here. It can be build to create unobvious blockades. You see it, if you look closely. And on the minimap it is shown too.
Making this water look the same leads to users beeing confused, why ships are not working as they should. I don't see a use case where hiding the blockades would be required...

I'd like some input from others on this before this is finally decided.

**Comment by Spikeone** [comment] 2016-02-29 13:19
Just my reasons as a state so far:
You can already build visible blockades for ships (small islands which separate).
If water is now used to also block but is also visible, there is no use at all.
Id like to suggest client only addons, players can switch if they like to see special water or not.

Just want to say the only problem was bad map design, placing harbors on land, HQs on water... that's what map testing is for, was done and I fixed the map.

**Comment by Flamefire** [comment] 2016-03-01 18:07
@MarcusSt @jhkl @Flow86 : Opinions?

**Comment by jhkl** [comment] 2016-03-01 22:03
I agreee with Flamefire. It is not intuitive for the user that terrain that looks the same has different properties.
Also I think it is too unimportant to add an extra addon, making the addon list more crowded.

**Comment by Spikeone** [comment] 2016-03-01 22:13
So, I guess the texture will stay the new way, replaced that water with sand just as I had to do before, still better than strange water.

http://www.rfmonline.de/rttr/spike/2-1-anywayz.zip

**Comment by Flamefire** [comment] 2016-03-02 07:44
I'm also against an addon...
@Spikeone: Don't just give up like that. Problem: Imagine "2" seas separated by unshippable water. You can build harbors on both of them but ships don't travel between those 2 harbors. If you cannot sea why, users will be confused and report bugs. If you can see it on the minimap, why not also show it on the map itself? Also the S2 editor also shows it like that so even map creators might assume it will look like that in the game. The color difference is really small and we can probably make it even smaller so it is less obvious, but it is still water, so it can be used for different (optical) effects than sand.

If water looks all the same, there is a big burden on map designers to make it (kind of) clear, where ships can't go. Not showing, why/where ships cannot go would be bad. But map designers still have an option when water looks the same: Our water is shaded. So he can use heights to make it darker/lighter with even better transitions to normal water. However you won't see that in the editor...

**Comment by Spikeone** [comment] 2016-03-02 08:54
Well as I understand reasons why this should be visible or why it should not I can totally agree that it might produce false issues, but they are map related and map designers should make sure that maps are working, gameplay and logical.

As this was my first attempt on using new textures and I failed. That's what we would needaptesters for but we don't have any, neither do we have map creators.

The additional water has only one use for me, block a path or ship building spot. That way I don't have to place a lot of objects to block a path, I can only set some but it is still reasonable. Also that way we could make endless maps act (for ships) as if they weren't.
As the same behavior could be achieved by placing small islands which seperate different areas (see pathfinding01) there would be no use for that water texture at all, although I also like the shallow water idea but that texture should be extra.

Because with the current version I would use that water only for blocking ship building spots and for coastal areas, which isn't that bad at all but invisible borders are just as great.

If you could just add an other texture (so we can have both) that'd be great as well - but then we come to the new map format etc. etc.

Means: I could use the old version for missions etc (as players shouldn't play those with explored maps, they can't see if something is connected or if it is not) but I would be a bit lazy and not use the new version.

**Comment by Flamefire** [comment] 2016-03-02 14:47
Suggestion: Lets introduce an RTTR map format that is similar to the S2 format. But we (for example) can introduce new textures or mix textures from different landscape types. This won't be for 0.8.3 but for near future (let's do more stable releases!)
For now, let's make this water type the same as in S2. How does it look in S2 ingame on the map and minimap? This will be how it should look like in RTTR for now.

**Comment by Spikeone** [comment] 2016-03-02 19:36
Yeah I agree with you that it should work as it did in S2, luckily it's working the way it was first implemented.
FYI: When saving a map in the original Mapeditor with that texture it was replaced by normal water, also the editor shows water as buildable.

![ingame](https://cloud.githubusercontent.com/assets/1276342/13472706/5b08ab04-e0b6-11e5-88fb-07392803bbf2.png)
![2](https://cloud.githubusercontent.com/assets/1276342/13472707/5c50c06e-e0b6-11e5-9e97-e3a2fa38059e.png)

**Comment by Flamefire** [comment] 2016-03-07 22:05
@Spikeone Water is now changed so all water types look the same (minimap and map)
Can you update your map again (with better design) so the "invisible borders" are somehow logical?

**Comment by Flamefire** [comment] 2016-05-08 16:32
@Spikeone Poke... ;-) Any news?

**Comment by Spikeone** [comment] 2016-05-08 16:55
The customer you are call is unavailable at the moment. Please try again later.

Yeah, I will update that terrain again.

**Comment by Spikeone** [comment] 2016-05-08 18:29
http://www.rfmonline.de/rttr/spike/anywayz.wld

had more trouble than I 'hoped' for...

**Comment by Flamefire** [comment] 2016-05-08 19:00
If you are happy with the map feel free to push it directly and close this :)

**Comment by Spikeone** [comment] 2016-05-08 19:08
Okay, later, I'll also push those other maps nobody reviewed (so sadly there is no way reviewing maps other than me and ingame "random" testers :-/)

**Closed** 2016-07-03 09:48 UTC
Labels: enhancement, map
