### ISSUE TITLE
Wrongly drawn terrain when starting a game

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1456] opened 2021-11-02 16:59 UTC
When starting a game, one has a strange black border at the bottom. By moving the camera just a bit this is fixed but strange anyway:

![grafik](https://user-images.githubusercontent.com/1276342/139911067-e375d367-b356-4df8-868a-6578381e8532.png)

**Comment by Flamefire** [comment] 2022-01-21 16:00
Some issues related to things like that were fixed with #1448 
Is this still an issue? With which map?

**Comment by Spikeone** [comment] 2022-01-21 20:10
@Flamefire still an issue, happens when using 800x600 resolution, but NOT if using 1920x1080

**Comment by Flamefire** [comment] 2022-01-22 10:42
Can't reproduce.
Which exact settings do you use?
- Map
- Exploration
- Window or fullscreen?

**Comment by Spikeone** [comment] 2022-01-22 12:39
```
[global]
version=13
gameversion=e6c99900dd0ce62cafa4c0ca555f25eba46bee45
submit_debug_data=2
use_upnp=2
smartCursor=1
debugMode=0

[video]
fullscreen_width=800
fullscreen_height=600
windowed_width=800
windowed_height=600
fullscreen=0
vsync=0
vbo=1
shared_textures=1

[language]
language=en

[driver]
video=(SDL2) OpenGL via SDL2-Library
audio=(SDL2) Audio via SDL2_mixer-Library

[sound]
musik=1
musik_volume=12
effekte=1
effekte_volume=25
playlist=F:\s25rttr_20210905\RTTR\MUSIC\S2_Standard.pll
```

**Comment by Flamefire** [comment] 2022-01-22 14:53
Found that it is related to "Optimized textures" (`shared_textures` in the config)
Disabling that fixes the issue.
Underlying issue is an uninitialized read for the max height. Fix is easy...

**Closed** 2022-01-24 05:58 UTC
Labels: bug
